import { describe, expect, it } from "vitest";

import {
  bigid,
  bigint,
  boolean,
  ColumnBuilder,
  type ColumnMeta,
  enumColumn,
  fk,
  id,
  integer,
  jsonb,
  SchemaBuildError,
  text,
  timestamp,
  uuid,
  varchar,
} from "../index";

describe("column constructors — storage metadata", () => {
  it.each([
    ["id", id(), { storageKind: "id", pgType: "int4", kind: "number" }],
    [
      "bigid",
      bigid(),
      { storageKind: "bigid", pgType: "int8", kind: "bigint" },
    ],
    ["text", text(), { storageKind: "text", pgType: "text", kind: "string" }],
    [
      "integer",
      integer(),
      { storageKind: "integer", pgType: "int4", kind: "number" },
    ],
    [
      "bigint",
      bigint(),
      { storageKind: "bigint", pgType: "int8", kind: "bigint" },
    ],
    [
      "boolean",
      boolean(),
      { storageKind: "boolean", pgType: "bool", kind: "boolean" },
    ],
    ["uuid", uuid(), { storageKind: "uuid", pgType: "uuid", kind: "uuid" }],
    ["jsonb", jsonb(), { storageKind: "jsonb", pgType: "jsonb", kind: "json" }],
  ])("%s carries the expected meta", (_label, builder, expected) => {
    expect(builder).toBeInstanceOf(ColumnBuilder);
    expect(builder._meta).toMatchObject(expected);
  });

  it("varchar defaults to length 255 and a clean pgType", () => {
    expect(varchar()._meta).toMatchObject({
      storageKind: "varchar",
      pgType: "varchar",
      varcharLength: 255,
    });
    expect(varchar(64)._meta.varcharLength).toBe(64);
  });

  it("timestamp toggles withTimezone and pgType", () => {
    expect(timestamp()._meta).toMatchObject({
      pgType: "timestamp",
      withTimezone: false,
    });
    expect(timestamp({ withTimezone: true })._meta).toMatchObject({
      pgType: "timestamptz",
      withTimezone: true,
    });
  });
});

describe("server-generated identity columns", () => {
  it.each([id(), bigid()])(
    "flags serial PKs as serverGenerated + primaryKey + hasDefault",
    (builder) => {
      expect(builder._meta.serverGenerated).toBe(true);
      expect(builder._meta.primaryKey).toBe(true);
      expect(builder._meta.hasDefault).toBe(true);
    },
  );

  it("non-identity columns are not server generated by default", () => {
    expect(text()._meta.serverGenerated).toBe(false);
    expect(text()._meta.primaryKey).toBe(false);
    expect(text()._meta.hasDefault).toBe(false);
  });
});

describe("modifier chain", () => {
  it("sets boolean flags and is chainable", () => {
    const col = text().notNull().unique().primaryKey().private().owner();
    const meta: ColumnMeta = col._meta;
    expect(meta).toMatchObject({
      notNull: true,
      unique: true,
      primaryKey: true,
      isPrivate: true,
      isOwner: true,
    });
  });
});

describe("default-expression stamping", () => {
  it("quotes and escapes string literals", () => {
    expect(text().default("active")._meta.defaultExpr).toBe("'active'");
    expect(text().default("O'Brien")._meta.defaultExpr).toBe("'O''Brien'");
  });

  it("stamps numeric and boolean literals verbatim", () => {
    expect(integer().default(0)._meta.defaultExpr).toBe("0");
    expect(boolean().default(true)._meta.defaultExpr).toBe("true");
    expect(boolean().default(false)._meta.defaultExpr).toBe("false");
  });

  it("stamps canonical now() / gen_random_uuid() expressions", () => {
    const ts = timestamp().defaultNow()._meta;
    expect(ts.defaultExpr).toBe("now()");
    expect(ts.defaultNow).toBe(true);

    const rand = uuid().defaultRandom()._meta;
    expect(rand.defaultExpr).toBe("gen_random_uuid()");
    expect(rand.defaultRandom).toBe(true);
  });

  it("records hasDefault and defaultValue for literals", () => {
    const col = integer().default(42)._meta;
    expect(col.hasDefault).toBe(true);
    expect(col.defaultValue).toBe(42);
  });
});

describe("referential-action modifiers", () => {
  it("are allowed on fk() columns", () => {
    const col = fk(() => ({
      __isColumnRef: true,
      tableName: "users",
      columnName: "id",
    }))
      .onDelete("cascade")
      .onUpdate("set null");
    expect(col._meta.onDelete).toBe("cascade");
    expect(col._meta.onUpdate).toBe("set null");
  });

  it("throw on non-fk columns", () => {
    expect(() => integer().onDelete("cascade")).toThrow(SchemaBuildError);
    expect(() => text().onUpdate("cascade")).toThrow(
      /only valid on fk\(\) columns/,
    );
  });
});

describe("enumColumn", () => {
  it("carries the enum name and values", () => {
    const col = enumColumn("status", ["active", "archived"]);
    expect(col._meta).toMatchObject({
      storageKind: "enum",
      enumName: "status",
      enumValues: ["active", "archived"],
      kind: "enum",
    });
  });

  it("throws when no values are provided", () => {
    expect(() => enumColumn("status", [])).toThrow(
      /requires at least one value/,
    );
  });
});
