import fs from "node:fs/promises";
import { WorkspaceClient } from "@databricks/sdk-experimental";
import { createLogger } from "../../logging/logger";
import type { EndpointConfig } from "../../plugins/serving/types";
import {
  hashSchema,
  loadServingCache,
  type ServingCache,
  saveServingCache,
} from "./cache";
import {
  convertRequestSchema,
  convertResponseSchema,
  deriveChunkType,
} from "./converter";
import { fetchOpenApiSchema } from "./fetcher";

const logger = createLogger("type-generator:serving");

interface GenerateServingTypesOptions {
  outFile: string;
  endpoints?: Record<string, EndpointConfig>;
  noCache?: boolean;
}

/**
 * Generates TypeScript type declarations for serving endpoints
 * by fetching their OpenAPI schemas and converting to TypeScript.
 */
export async function generateServingTypes(
  options: GenerateServingTypesOptions,
): Promise<void> {
  const { outFile, noCache } = options;

  // Resolve endpoints from config or env
  const endpoints = options.endpoints ?? resolveDefaultEndpoints();
  if (Object.keys(endpoints).length === 0) {
    logger.debug("No serving endpoints configured, skipping type generation");
    return;
  }

  logger.debug(
    "Starting serving type generation for %d endpoint(s)",
    Object.keys(endpoints).length,
  );

  const cache = noCache
    ? { version: "1", endpoints: {} }
    : await loadServingCache();

  const client = new WorkspaceClient({});
  let updated = false;

  const registryEntries: string[] = [];

  for (const [alias, config] of Object.entries(endpoints)) {
    const endpointName = process.env[config.env];
    if (!endpointName) {
      logger.warn(
        "Skipping alias '%s': env var '%s' is not set",
        alias,
        config.env,
      );
      continue;
    }

    const result = await fetchOpenApiSchema(
      client,
      endpointName,
      config.servedModel,
    );
    if (!result) continue;

    const { spec, pathKey } = result;
    const schemaJson = JSON.stringify(spec);
    const hash = hashSchema(schemaJson);

    // Check cache
    const cached = cache.endpoints[alias];
    if (cached && cached.hash === hash) {
      logger.debug("Cache hit for '%s', using cached types", alias);
      registryEntries.push(
        buildRegistryEntry(
          alias,
          cached.requestType,
          cached.responseType,
          cached.chunkType,
        ),
      );
      continue;
    }

    // Cache miss — convert
    logger.debug("Converting OpenAPI schema for '%s'", alias);
    const operation = spec.paths[pathKey]?.post;
    if (!operation) {
      logger.warn(
        "No POST operation found at path '%s' for '%s'",
        pathKey,
        alias,
      );
      continue;
    }

    const requestType = convertRequestSchema(operation);
    const responseType = convertResponseSchema(operation);
    const chunkType = deriveChunkType(operation);

    cache.endpoints[alias] = { hash, requestType, responseType, chunkType };
    updated = true;

    registryEntries.push(
      buildRegistryEntry(alias, requestType, responseType, chunkType),
    );
  }

  if (registryEntries.length === 0) {
    logger.debug("No serving types generated");
    return;
  }

  const output = generateTypeDeclarations(registryEntries);
  await fs.writeFile(outFile, output, "utf-8");
  logger.debug("Wrote serving types to %s", outFile);

  if (updated) {
    await saveServingCache(cache as ServingCache);
    logger.debug("Updated serving types cache");
  }
}

function resolveDefaultEndpoints(): Record<string, EndpointConfig> {
  if (process.env.DATABRICKS_SERVING_ENDPOINT) {
    return { default: { env: "DATABRICKS_SERVING_ENDPOINT" } };
  }
  return {};
}

function buildRegistryEntry(
  alias: string,
  requestType: string,
  responseType: string,
  chunkType: string | null,
): string {
  const indent = "      ";
  const chunkEntry = chunkType ? chunkType : "unknown";
  return `    ${alias}: {
${indent}request: ${indentType(requestType, indent)};
${indent}response: ${indentType(responseType, indent)};
${indent}chunk: ${indentType(chunkEntry, indent)};
    };`;
}

function indentType(typeStr: string, baseIndent: string): string {
  if (!typeStr.includes("\n")) return typeStr;
  return typeStr
    .split("\n")
    .map((line, i) => (i === 0 ? line : `${baseIndent}${line}`))
    .join("\n");
}

function generateTypeDeclarations(entries: string[]): string {
  return `// Auto-generated by AppKit - DO NOT EDIT
// Generated from serving endpoint OpenAPI schemas
import "@databricks/appkit";

declare module "@databricks/appkit" {
  interface ServingEndpointRegistry {
${entries.join("\n")}
  }
}
`;
}
