/**
 * Resource Registry Type System
 *
 * This module defines the type system for the AppKit Resource Registry,
 * which enables plugins to declare their Databricks resource requirements
 * in a machine-readable format.
 *
 * Base interfaces (ResourceFieldEntry, ResourceRequirement, PluginManifest)
 * are generated from plugin-manifest.schema.json and imported via shared.
 * This module re-exports them with strict narrowing (ResourceType enum,
 * ResourcePermission union) for appkit-internal use.
 *
 * Resource types, permissions, and hierarchy constants are generated by
 * tools/generate-registry-types.ts into types.generated.ts.
 */

// Re-export generated registry types (enum + const must be value exports for runtime)
import {
  PERMISSION_HIERARCHY_BY_TYPE,
  PERMISSIONS_BY_TYPE,
  type ResourcePermission,
  ResourceType,
} from "./types.generated";

export {
  PERMISSION_HIERARCHY_BY_TYPE,
  PERMISSIONS_BY_TYPE,
  ResourceType,
  type ResourcePermission,
};

// Re-export generated base type from shared (schema-derived, used directly).
export type { ResourceFieldEntry } from "shared";

// Import shared base types for strict extension below.
import type {
  PluginManifest as SharedPluginManifest,
  ResourceRequirement as SharedResourceRequirement,
} from "shared";

// ============================================================================
// Strict appkit wrappers — narrow generated base types for registry use
// ============================================================================

/**
 * Declares a resource requirement for a plugin.
 * Can be defined statically in a manifest or dynamically via getResourceRequirements().
 * Narrows the generated base: type → ResourceType enum, permission → ResourcePermission union.
 *
 * @see `packages/shared/src/schemas/plugin-manifest.generated.ts` `ResourceRequirement` — generated base
 * @see {@link SharedResourceRequirement} — shared re-export with runtime `fields` and `required`
 */
export interface ResourceRequirement extends SharedResourceRequirement {
  /** Type of Databricks resource required (narrowed to enum) */
  type: ResourceType;

  /** Required permission level for the resource (narrowed to union) */
  permission: ResourcePermission;
}

/**
 * Internal representation of a resource in the registry.
 * Extends ResourceRequirement with resolution state and plugin ownership.
 */
export interface ResourceEntry extends ResourceRequirement {
  /** Plugin(s) that require this resource (comma-separated if multiple) */
  plugin: string;

  /** Whether the resource has been resolved (all field env vars set) */
  resolved: boolean;

  /** Resolved value per field name. Populated by validate() when all field env vars are set. */
  values?: Record<string, string>;

  /**
   * Per-plugin permission tracking.
   * Maps plugin name to the permission it originally requested.
   * Populated when multiple plugins share the same resource.
   */
  permissionSources?: Record<string, ResourcePermission>;
}

/**
 * Result of validating all registered resources against the environment.
 */
export interface ValidationResult {
  /** Whether all required resources are available */
  valid: boolean;

  /** List of missing required resources */
  missing: ResourceEntry[];

  /** Complete list of all registered resources (required and optional) */
  all: ResourceEntry[];
}

import type { JSONSchema7 } from "json-schema";

/**
 * Configuration schema definition for plugin config.
 * Re-exported from the standard JSON Schema Draft 7 types.
 *
 * @see {@link https://json-schema.org/draft-07/json-schema-release-notes | JSON Schema Draft 7}
 */
export type ConfigSchema = JSONSchema7;

/**
 * Plugin manifest that declares metadata and resource requirements.
 * Attached to plugin classes as a static property.
 * Extends the shared PluginManifest with strict resource types.
 *
 * @see `packages/shared/src/schemas/plugin-manifest.generated.ts` `PluginManifest` — generated base
 * @see {@link SharedPluginManifest} — shared re-export with JSONSchema7 config
 */
export interface PluginManifest<TName extends string = string>
  extends Omit<SharedPluginManifest, "resources" | "config"> {
  /** Plugin identifier — the single source of truth for the plugin's name */
  name: TName;

  /**
   * Resource requirements declaration (with strict ResourceRequirement types)
   */
  resources: {
    /** Resources that must be available for the plugin to function */
    required: Omit<ResourceRequirement, "required">[];

    /** Resources that enhance functionality but are not mandatory */
    optional: Omit<ResourceRequirement, "required">[];
  };

  /**
   * Configuration schema for the plugin.
   * Uses JSONSchema7 instead of the generated ConfigSchema (which is too restrictive).
   */
  config?: {
    schema: ConfigSchema;
  };
}
