#!/usr/bin/env node
/**
 * AppKit DevTools MCP channel server.
 *
 * A lightweight stdio MCP server that polls the AppKit devtools endpoint
 * and pushes new context into the active Claude Code / Isaac session
 * via the claude/channel protocol.
 *
 * Registration:
 *   claude mcp add --scope user --transport stdio appkit-devtools -- node <path>/channel-server.js
 *
 * Usage:
 *   claude --dangerously-load-development-channels server:appkit-devtools
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  ListToolsRequestSchema,
  CallToolRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const DEFAULT_APP_PORT = 8000;
const POLL_INTERVAL_MS = 1000;

function getDevtoolsUrl(): string {
  if (process.env.DEVTOOLS_URL) return process.env.DEVTOOLS_URL;
  const port =
    process.env.DATABRICKS_APP_PORT || process.env.PORT || DEFAULT_APP_PORT;
  return `http://localhost:${port}/api/devtools`;
}

function log(msg: string) {
  console.error(`[appkit-channel] ${msg}`);
}

const baseUrl = getDevtoolsUrl();
let lastReceivedAt = "";

const mcp = new Server(
  { name: "appkit-devtools", version: "0.1.0" },
  {
    capabilities: {
      experimental: { "claude/channel": {} },
      tools: {},
    },
    instructions: `You are connected to an AppKit DevTools channel. When a developer picks a UI element in their browser and describes a change, the context is pushed directly to you. Act on it immediately — the prompt contains the element details, source location, route, and the user's request.

Available tools:
- get_devtools_context: Fetch the latest context bundle from the running AppKit app
- get_devtools_prompt: Fetch the latest AI prompt (same as 'npx appkit inspect prompt')`,
  },
);

const TOOLS = [
  {
    name: "get_devtools_context",
    description:
      "Fetch the latest devtools context bundle from the running AppKit app. Returns the full bundle with page info, picked element, network activity, and server events.",
    inputSchema: {
      type: "object" as const,
      properties: {},
    },
  },
  {
    name: "get_devtools_prompt",
    description:
      "Fetch the latest AI prompt generated by the devtools. This is the same output as 'npx appkit inspect prompt' — a self-contained prompt with element details and the user's request.",
    inputSchema: {
      type: "object" as const,
      properties: {},
    },
  },
];

mcp.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

mcp.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name } = req.params;

  if (name === "get_devtools_context") {
    try {
      const res = await fetch(`${baseUrl}/last`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      return {
        content: [
          { type: "text" as const, text: JSON.stringify(data, null, 2) },
        ],
      };
    } catch (e) {
      return {
        content: [
          {
            type: "text" as const,
            text: `Failed to fetch context: ${e instanceof Error ? e.message : String(e)}`,
          },
        ],
        isError: true,
      };
    }
  }

  if (name === "get_devtools_prompt") {
    try {
      const res = await fetch(`${baseUrl}/last-prompt`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const text = await res.text();
      return { content: [{ type: "text" as const, text }] };
    } catch (e) {
      return {
        content: [
          {
            type: "text" as const,
            text: `Failed to fetch prompt: ${e instanceof Error ? e.message : String(e)}`,
          },
        ],
        isError: true,
      };
    }
  }

  throw new Error(`Unknown tool: ${name}`);
});

async function pollAndPush() {
  try {
    const res = await fetch(`${baseUrl}/last`);
    if (!res.ok) return;

    const data = (await res.json()) as {
      prompt?: string;
      receivedAt?: string;
    };

    if (!data.receivedAt || data.receivedAt === lastReceivedAt) return;
    if (!data.prompt) return;

    lastReceivedAt = data.receivedAt;

    await mcp.notification({
      method: "notifications/claude/channel",
      params: { content: data.prompt },
    });

    log(`Pushed prompt (${data.prompt.length} chars)`);
  } catch {
    // Server might not be running yet — silent retry
  }
}

async function main() {
  log(`Devtools URL: ${baseUrl}`);

  await mcp.connect(new StdioServerTransport());
  log("MCP connected");

  const pollTimer = setInterval(pollAndPush, POLL_INTERVAL_MS);

  const cleanup = () => {
    clearInterval(pollTimer);
    process.exit(0);
  };

  process.on("SIGINT", cleanup);
  process.on("SIGTERM", cleanup);
}

main().catch((e) => {
  log(`Fatal: ${e instanceof Error ? e.message : String(e)}`);
  process.exit(1);
});
