// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file appkit/v1/common.proto (package appkit.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

export const file_appkit_v1_common: GenFile =
  /*@__PURE__*/ fileDesc("ChZhcHBraXQvdjEvY29tbW9uLnByb3RvEglhcHBraXQudjE");

/** @generated from message appkit.v1.Error */
export type Error$ = Message<"appkit.v1.Error"> & {
  code: number;
  message: string;
  details: { [key: string]: string };
};
export const Error$Schema: GenMessage<Error$> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_common, 0);

/** @generated from message appkit.v1.PageRequest */
export type PageRequest = Message<"appkit.v1.PageRequest"> & {
  pageSize: number;
  pageToken: string;
};
export const PageRequestSchema: GenMessage<PageRequest> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_common, 1);

/** @generated from message appkit.v1.PageResponse */
export type PageResponse = Message<"appkit.v1.PageResponse"> & {
  nextPageToken: string;
  totalSize: number;
};
export const PageResponseSchema: GenMessage<PageResponse> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_common, 2);

/** @generated from message appkit.v1.Metadata */
export type Metadata = Message<"appkit.v1.Metadata"> & {
  entries: { [key: string]: string };
};
export const MetadataSchema: GenMessage<Metadata> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_common, 3);

/** @generated from message appkit.v1.Value */
export type Value = Message<"appkit.v1.Value"> & {
  kind:
    | { case: "stringValue"; value: string }
    | { case: "numberValue"; value: number }
    | { case: "boolValue"; value: boolean }
    | { case: "bytesValue"; value: Uint8Array }
    | { case: "intValue"; value: bigint }
    | { case: "timestampValue"; value: Timestamp }
    | { case: undefined; value?: undefined };
};
export const ValueSchema: GenMessage<Value> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_common, 4);
