// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file appkit/v1/common.proto (package appkit.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import { proto3 } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

export const file_appkit_v1_common: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChZhcHBraXQvdjEvY29tbW9uLnByb3RvEglhcHBraXQudjE",
  );

/**
 * Standard error envelope for structured error reporting across services.
 *
 * @generated from message appkit.v1.Error
 */
export type Error$ = Message<"appkit.v1.Error"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;
  /**
   * @generated from field: string message = 2;
   */
  message: string;
  /**
   * @generated from field: map<string, string> details = 3;
   */
  details: { [key: string]: string };
};

export const Error$Schema: GenMessage<Error$> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_common, 0);

/**
 * Pagination request parameters.
 *
 * @generated from message appkit.v1.PageRequest
 */
export type PageRequest = Message<"appkit.v1.PageRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;
  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

export const PageRequestSchema: GenMessage<PageRequest> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_common, 1);

/**
 * Pagination response metadata.
 *
 * @generated from message appkit.v1.PageResponse
 */
export type PageResponse = Message<"appkit.v1.PageResponse"> & {
  /**
   * @generated from field: string next_page_token = 1;
   */
  nextPageToken: string;
  /**
   * @generated from field: int32 total_size = 2;
   */
  totalSize: number;
};

export const PageResponseSchema: GenMessage<PageResponse> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_common, 2);

/**
 * Generic key-value metadata bag.
 *
 * @generated from message appkit.v1.Metadata
 */
export type Metadata = Message<"appkit.v1.Metadata"> & {
  /**
   * @generated from field: map<string, string> entries = 1;
   */
  entries: { [key: string]: string };
};

export const MetadataSchema: GenMessage<Metadata> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_common, 3);

/**
 * A flexible value type for heterogeneous data.
 *
 * @generated from message appkit.v1.Value
 */
export type Value = Message<"appkit.v1.Value"> & {
  /**
   * @generated from oneof appkit.v1.Value.kind
   */
  kind:
    | { case: "stringValue"; value: string }
    | { case: "numberValue"; value: number }
    | { case: "boolValue"; value: boolean }
    | { case: "bytesValue"; value: Uint8Array }
    | { case: "intValue"; value: bigint }
    | { case: "timestampValue"; value: Timestamp }
    | { case: undefined; value?: undefined };
};

export const ValueSchema: GenMessage<Value> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_common, 4);
