// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file appkit/v1/pipeline.proto (package appkit.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import { proto3 } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Error$, Metadata, Value } from "./common_pb";
import { file_appkit_v1_common } from "./common_pb";

export const file_appkit_v1_pipeline: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChhhcHBraXQvdjEvcGlwZWxpbmUucHJvdG8SCWFwcGtpdC52MQ",
  );

/**
 * Status of a pipeline job execution.
 *
 * @generated from enum appkit.v1.JobStatus
 */
export enum JobStatus {
  UNSPECIFIED = 0,
  PENDING = 1,
  RUNNING = 2,
  SUCCESS = 3,
  FAILED = 4,
  CANCELLED = 5,
}

export const JobStatusSchema: GenEnum<JobStatus> =
  /*@__PURE__*/
  enumDesc(file_appkit_v1_pipeline, 0);

/**
 * A single row of structured data produced by a pipeline stage.
 *
 * @generated from message appkit.v1.DataRow
 */
export type DataRow = Message<"appkit.v1.DataRow"> & {
  /**
   * @generated from field: map<string, appkit.v1.Value> fields = 1;
   */
  fields: { [key: string]: Value };
};

export const DataRowSchema: GenMessage<DataRow> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_pipeline, 0);

/**
 * Result of a pipeline job execution.
 *
 * @generated from message appkit.v1.JobResult
 */
export type JobResult = Message<"appkit.v1.JobResult"> & {
  /**
   * @generated from field: string job_run_id = 1;
   */
  jobRunId: string;
  /**
   * @generated from field: string job_id = 2;
   */
  jobId: string;
  /**
   * @generated from field: appkit.v1.JobStatus status = 3;
   */
  status: JobStatus;
  /**
   * @generated from field: google.protobuf.Timestamp started_at = 4;
   */
  startedAt?: Timestamp;
  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 5;
   */
  completedAt?: Timestamp;
  /**
   * @generated from field: repeated appkit.v1.DataRow rows = 6;
   */
  rows: DataRow[];
  /**
   * @generated from field: appkit.v1.Metadata metadata = 7;
   */
  metadata?: Metadata;
  /**
   * @generated from field: appkit.v1.Error error = 8;
   */
  error?: Error$;
};

export const JobResultSchema: GenMessage<JobResult> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_pipeline, 1);

/**
 * A batch of rows for efficient bulk transfer between pipeline stages.
 *
 * @generated from message appkit.v1.DataBatch
 */
export type DataBatch = Message<"appkit.v1.DataBatch"> & {
  /**
   * @generated from field: string batch_id = 1;
   */
  batchId: string;
  /**
   * @generated from field: string source_stage = 2;
   */
  sourceStage: string;
  /**
   * @generated from field: string target_stage = 3;
   */
  targetStage: string;
  /**
   * @generated from field: repeated appkit.v1.DataRow rows = 4;
   */
  rows: DataRow[];
  /**
   * @generated from field: appkit.v1.Metadata metadata = 5;
   */
  metadata?: Metadata;
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;
};

export const DataBatchSchema: GenMessage<DataBatch> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_pipeline, 2);

/**
 * Schema definition for a pipeline stage's input or output.
 *
 * @generated from message appkit.v1.StageSchema
 */
export type StageSchema = Message<"appkit.v1.StageSchema"> & {
  /**
   * @generated from field: string stage_name = 1;
   */
  stageName: string;
  /**
   * @generated from field: repeated appkit.v1.FieldDescriptor fields = 2;
   */
  fields: FieldDescriptor[];
};

export const StageSchemaSchema: GenMessage<StageSchema> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_pipeline, 3);

/**
 * Describes a single field in a stage schema.
 *
 * @generated from message appkit.v1.FieldDescriptor
 */
export type FieldDescriptor = Message<"appkit.v1.FieldDescriptor"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
  /**
   * @generated from field: appkit.v1.FieldType type = 2;
   */
  type: FieldType;
  /**
   * @generated from field: bool required = 3;
   */
  required: boolean;
  /**
   * @generated from field: string description = 4;
   */
  description: string;
};

export const FieldDescriptorSchema: GenMessage<FieldDescriptor> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_pipeline, 4);

/**
 * Supported field types for stage schemas.
 *
 * @generated from enum appkit.v1.FieldType
 */
export enum FieldType {
  UNSPECIFIED = 0,
  STRING = 1,
  NUMBER = 2,
  BOOLEAN = 3,
  BYTES = 4,
  INTEGER = 5,
  TIMESTAMP = 6,
}

export const FieldTypeSchema: GenEnum<FieldType> =
  /*@__PURE__*/
  enumDesc(file_appkit_v1_pipeline, 1);
