// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file appkit/v1/pipeline.proto (package appkit.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { Error$, Metadata, Value } from "./common_pb";

export const file_appkit_v1_pipeline: GenFile =
  /*@__PURE__*/ fileDesc("ChhhcHBraXQvdjEvcGlwZWxpbmUucHJvdG8SCWFwcGtpdC52MQ");

/** @generated from enum appkit.v1.JobStatus */
export enum JobStatus {
  UNSPECIFIED = 0,
  PENDING = 1,
  RUNNING = 2,
  SUCCESS = 3,
  FAILED = 4,
  CANCELLED = 5,
}
export const JobStatusSchema: GenEnum<JobStatus> =
  /*@__PURE__*/ enumDesc(file_appkit_v1_pipeline, 0);

/** @generated from message appkit.v1.DataRow */
export type DataRow = Message<"appkit.v1.DataRow"> & {
  fields: { [key: string]: Value };
};
export const DataRowSchema: GenMessage<DataRow> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_pipeline, 0);

/** @generated from message appkit.v1.JobResult */
export type JobResult = Message<"appkit.v1.JobResult"> & {
  jobRunId: string;
  jobId: string;
  status: JobStatus;
  startedAt?: Timestamp;
  completedAt?: Timestamp;
  rows: DataRow[];
  metadata?: Metadata;
  error?: Error$;
};
export const JobResultSchema: GenMessage<JobResult> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_pipeline, 1);

/** @generated from message appkit.v1.DataBatch */
export type DataBatch = Message<"appkit.v1.DataBatch"> & {
  batchId: string;
  sourceStage: string;
  targetStage: string;
  rows: DataRow[];
  metadata?: Metadata;
  createdAt?: Timestamp;
};
export const DataBatchSchema: GenMessage<DataBatch> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_pipeline, 2);

/** @generated from message appkit.v1.StageSchema */
export type StageSchema = Message<"appkit.v1.StageSchema"> & {
  stageName: string;
  fields: FieldDescriptor[];
};
export const StageSchemaSchema: GenMessage<StageSchema> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_pipeline, 3);

/** @generated from message appkit.v1.FieldDescriptor */
export type FieldDescriptor = Message<"appkit.v1.FieldDescriptor"> & {
  name: string;
  type: FieldType;
  required: boolean;
  description: string;
};
export const FieldDescriptorSchema: GenMessage<FieldDescriptor> =
  /*@__PURE__*/ messageDesc(file_appkit_v1_pipeline, 4);

/** @generated from enum appkit.v1.FieldType */
export enum FieldType {
  UNSPECIFIED = 0,
  STRING = 1,
  NUMBER = 2,
  BOOLEAN = 3,
  BYTES = 4,
  INTEGER = 5,
  TIMESTAMP = 6,
}
export const FieldTypeSchema: GenEnum<FieldType> =
  /*@__PURE__*/ enumDesc(file_appkit_v1_pipeline, 1);
