// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file appkit/v1/services.proto (package appkit.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import { proto3 } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type {
  DataBatch,
  Error$,
  JobResult,
  PageRequest,
  PageResponse,
  StageSchema,
} from "./pipeline_pb";
import { file_appkit_v1_pipeline } from "./pipeline_pb";
import { file_appkit_v1_common } from "./common_pb";

export const file_appkit_v1_services: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChlhcHBraXQvdjEvc2VydmljZXMucHJvdG8SCWFwcGtpdC52MQ",
  );

/**
 * Service for retrieving pipeline job results.
 *
 * @generated from service appkit.v1.JobDataService
 */
export const JobDataService: GenService<{
  /**
   * Get the result of a specific job run.
   *
   * @generated from rpc appkit.v1.JobDataService.GetJobResult
   */
  getJobResult: {
    input: GetJobResultRequest;
    output: JobResult;
  };
  /**
   * Stream job results as they complete.
   *
   * @generated from rpc appkit.v1.JobDataService.StreamJobResults
   */
  streamJobResults: {
    input: StreamJobResultsRequest;
    output: JobResult;
  };
  /**
   * Submit a batch of data to a pipeline stage.
   *
   * @generated from rpc appkit.v1.JobDataService.SubmitBatch
   */
  submitBatch: {
    input: SubmitBatchRequest;
    output: SubmitBatchResponse;
  };
}> = /*@__PURE__*/ serviceDesc(file_appkit_v1_services, 0);

/**
 * Service for pipeline stage coordination.
 *
 * @generated from service appkit.v1.PipelineService
 */
export const PipelineService: GenService<{
  /**
   * Get the schema for a pipeline stage.
   *
   * @generated from rpc appkit.v1.PipelineService.GetStageSchema
   */
  getStageSchema: {
    input: GetStageSchemaRequest;
    output: StageSchema;
  };
  /**
   * List available pipeline stages.
   *
   * @generated from rpc appkit.v1.PipelineService.ListStages
   */
  listStages: {
    input: ListStagesRequest;
    output: ListStagesResponse;
  };
}> = /*@__PURE__*/ serviceDesc(file_appkit_v1_services, 1);

/**
 * @generated from message appkit.v1.GetJobResultRequest
 */
export type GetJobResultRequest = Message<"appkit.v1.GetJobResultRequest"> & {
  /**
   * @generated from field: string job_run_id = 1;
   */
  jobRunId: string;
};

export const GetJobResultRequestSchema: GenMessage<GetJobResultRequest> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_services, 0);

/**
 * @generated from message appkit.v1.StreamJobResultsRequest
 */
export type StreamJobResultsRequest =
  Message<"appkit.v1.StreamJobResultsRequest"> & {
    /**
     * @generated from field: string job_id = 1;
     */
    jobId: string;
    /**
     * @generated from field: google.protobuf.Timestamp since = 2;
     */
    since?: Timestamp;
    /**
     * @generated from field: int32 max_results = 3;
     */
    maxResults: number;
  };

export const StreamJobResultsRequestSchema: GenMessage<StreamJobResultsRequest> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_services, 1);

/**
 * @generated from message appkit.v1.SubmitBatchRequest
 */
export type SubmitBatchRequest = Message<"appkit.v1.SubmitBatchRequest"> & {
  /**
   * @generated from field: appkit.v1.DataBatch batch = 1;
   */
  batch?: DataBatch;
};

export const SubmitBatchRequestSchema: GenMessage<SubmitBatchRequest> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_services, 2);

/**
 * @generated from message appkit.v1.SubmitBatchResponse
 */
export type SubmitBatchResponse = Message<"appkit.v1.SubmitBatchResponse"> & {
  /**
   * @generated from field: bool accepted = 1;
   */
  accepted: boolean;
  /**
   * @generated from field: string batch_id = 2;
   */
  batchId: string;
  /**
   * @generated from field: appkit.v1.Error error = 3;
   */
  error?: Error$;
};

export const SubmitBatchResponseSchema: GenMessage<SubmitBatchResponse> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_services, 3);

/**
 * @generated from message appkit.v1.GetStageSchemaRequest
 */
export type GetStageSchemaRequest =
  Message<"appkit.v1.GetStageSchemaRequest"> & {
    /**
     * @generated from field: string stage_name = 1;
     */
    stageName: string;
  };

export const GetStageSchemaRequestSchema: GenMessage<GetStageSchemaRequest> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_services, 4);

/**
 * @generated from message appkit.v1.ListStagesRequest
 */
export type ListStagesRequest = Message<"appkit.v1.ListStagesRequest"> & {
  /**
   * @generated from field: appkit.v1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;
};

export const ListStagesRequestSchema: GenMessage<ListStagesRequest> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_services, 5);

/**
 * @generated from message appkit.v1.ListStagesResponse
 */
export type ListStagesResponse = Message<"appkit.v1.ListStagesResponse"> & {
  /**
   * @generated from field: repeated appkit.v1.StageSchema stages = 1;
   */
  stages: StageSchema[];
  /**
   * @generated from field: appkit.v1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;
};

export const ListStagesResponseSchema: GenMessage<ListStagesResponse> =
  /*@__PURE__*/
  messageDesc(file_appkit_v1_services, 6);
