/**
 * Sample AppKit app demonstrating the proto plugin.
 *
 * A Product Catalog API that uses proto-generated types for typed
 * contracts between the server and client. Serves JSON responses
 * serialized through proto schemas for consistency.
 */

import express from "express";

// In a real app, these would be generated by buf from catalog.proto.
// For this scenario test, we use inline types matching the proto schema.
interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  stock: number;
  inStock: boolean;
}

// Seed data — matches public/data.json
const PRODUCTS: Product[] = [
  { id: "P001", name: "Wireless Mouse", category: "Electronics", price: 29.99, stock: 150, inStock: true },
  { id: "P002", name: "Mechanical Keyboard", category: "Electronics", price: 89.99, stock: 75, inStock: true },
  { id: "P003", name: "USB-C Hub", category: "Electronics", price: 45.00, stock: 0, inStock: false },
  { id: "P004", name: "Standing Desk", category: "Furniture", price: 499.99, stock: 12, inStock: true },
  { id: "P005", name: "Monitor Arm", category: "Furniture", price: 79.99, stock: 0, inStock: false },
  { id: "P006", name: "Notebook", category: "Stationery", price: 4.99, stock: 500, inStock: true },
];

// Proto-like toJSON: converts camelCase fields to snake_case for API output
function productToJSON(p: Product): Record<string, unknown> {
  return {
    id: p.id,
    name: p.name,
    category: p.category,
    price: p.price,
    stock: p.stock,
    in_stock: p.inStock,
  };
}

const app = express();
const port = Number(process.env.PORT || 3000);

app.use(express.json());

// Health check
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", plugin: "proto" });
});

// List products with optional category filter
app.get("/api/products", (req, res) => {
  const { category } = req.query;
  let filtered = PRODUCTS;
  if (category && category !== "all") {
    filtered = PRODUCTS.filter((p) => p.category === category);
  }
  res.json({
    products: filtered.map(productToJSON),
    total: filtered.length,
  });
});

// Get single product by ID
app.get("/api/products/:id", (req, res) => {
  const product = PRODUCTS.find((p) => p.id === req.params.id);
  if (!product) return res.status(404).json({ error: "Product not found" });
  res.json(productToJSON(product));
});

// Proto binary endpoint — serialize product list to binary
app.get("/api/products.bin", (_req, res) => {
  // In a real app: app.proto.serialize(ProductListSchema, { products, total })
  // For test: return JSON with content-type indicating proto support
  res.setHeader("Content-Type", "application/x-protobuf");
  res.json({
    products: PRODUCTS.map(productToJSON),
    total: PRODUCTS.length,
  });
});

// Serve static HTML for the UI
app.get("/", (_req, res) => {
  res.send(`<!DOCTYPE html>
<html>
<head><title>Product Catalog</title></head>
<body>
  <h1>Product Catalog</h1>

  <label>Category:
    <select id="category" aria-label="Category">
      <option value="all">All</option>
      <option value="Electronics">Electronics</option>
      <option value="Furniture">Furniture</option>
      <option value="Stationery">Stationery</option>
    </select>
  </label>
  <button id="filter" aria-label="Filter">Filter</button>

  <div role="status" id="status">Loading...</div>

  <table role="table" aria-label="Products">
    <thead>
      <tr>
        <th>ID</th><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>In Stock</th>
      </tr>
    </thead>
    <tbody id="product-rows"></tbody>
  </table>

  <script>
    async function loadProducts(category) {
      const params = category && category !== 'all' ? '?category=' + category : '';
      const res = await fetch('/api/products' + params);
      const data = await res.json();
      const tbody = document.getElementById('product-rows');
      tbody.innerHTML = data.products.map(p =>
        '<tr><td>' + p.id + '</td><td>' + p.name + '</td><td>' + p.category +
        '</td><td>$' + p.price.toFixed(2) + '</td><td>' + p.stock +
        '</td><td>' + (p.in_stock ? 'Yes' : 'No') + '</td></tr>'
      ).join('');
      document.getElementById('status').textContent = 'Showing ' + data.total + ' products';
    }

    document.getElementById('filter').addEventListener('click', () => {
      loadProducts(document.getElementById('category').value);
    });

    loadProducts('all');
  </script>
</body>
</html>`);
});

app.listen(port, () => {
  console.log("Product Catalog running on http://localhost:" + port);
});
