import fsSync from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The typegen cache, embedded in the generated `.d.ts` files themselves.
 *
 * A generated file has two parts this module reads and writes:
 *
 *   1. A **header comment** listing one `name → hash` per generated entry.
 *      The hash is a change detector: it matches iff the entry's source
 *      (SQL text / `source|lane` / endpoint identity) is unchanged.
 *   2. The **body**, a `declare module { interface <Registry> { ... } }` whose
 *      members are the rendered type blocks, one per entry.
 *
 * Together they act as a cache: on a later run, an entry whose current hash
 * matches the header is a HIT — its rendered block is reused verbatim from the
 * body, with no workspace call. Because the file is committed to the app repo,
 * an unchanged run touches the workspace zero times. Degraded / `unknown`
 * entries are omitted from the header, so they always read as a MISS and get
 * re-described on the next successful pass.
 *
 * Entry points (each subsystem's generator/loader calls these):
 *   - {@link renderCacheHeader}     build the header block for a fresh file
 *   - {@link resolveHeaderTimestamp} keep the timestamp stable on unchanged runs
 *   - {@link parseCacheHeader}      read `name → hash` back from a committed file
 *   - {@link splitEntryBlocks}      read `name → rendered block` from the body
 *   - {@link objectMemberValue} / {@link objectTopLevelKeys}
 *                                   inspect a rendered block (serving allowlist)
 *
 * The rest of the module is a small string/comment-aware TypeScript scanner
 * used by those functions so braces inside strings or comments never corrupt
 * member boundaries.
 */

// Marker lines that bound the machine-readable region of the header. The
// leading rule embeds the cache version + tool version + timestamp; the
// trailing rule closes the entry table. Parsing keys off these exact prefixes.
const OPEN_RULE_PREFIX = "// ── typegen cache";
const CLOSE_RULE = `// ${"─".repeat(60)}`;

export interface CacheHeaderEntry {
  /** Logical entry name (query key, metric key, serving alias). */
  name: string;
  /** Local change-detector hash (hex). */
  hash: string;
  /**
   * Optional decorative middle columns shown between name and hash (e.g.
   * `source · lane` for metric views). Ignored by the parser, which only
   * reads the first (name) and last (hash) tokens of each entry line.
   */
  detail?: string;
}

interface RenderCacheHeaderOptions {
  /** Cache-format version for this subsystem (queries/metrics "3", serving "1"). */
  version: string;
  /** One-line human explanation of what a matching hash skips. */
  explainer: string;
  /** Successfully-generated entries (name + hash [+ decorative detail]). */
  entries: CacheHeaderEntry[];
  /** ISO timestamp; defaults to now. Only changes when the file is rewritten. */
  timestamp?: string;
  /** Tool version string; defaults to the resolved `@databricks/appkit` version. */
  toolVersion?: string;
}

/**
 * Render the cache header comment block that precedes the imports in every
 * generated `.d.ts`. Ends with a trailing newline so it can be prepended
 * directly to the file body.
 */
export function renderCacheHeader(opts: RenderCacheHeaderOptions): string {
  const timestamp = opts.timestamp ?? new Date().toISOString();
  const toolVersion = opts.toolVersion ?? getAppkitVersion();

  const lines: string[] = [
    "// Auto-generated by AppKit — DO NOT EDIT",
    "// Regenerate with: npx @databricks/appkit generate-types",
    "//",
    `${OPEN_RULE_PREFIX} · v${opts.version} · appkit@${toolVersion} · ${timestamp} ──`,
    `// ${opts.explainer}`,
  ];

  if (opts.entries.length > 0) {
    // Align the hash column: pad the visible "name + detail" prefix to a
    // common width so the table scans cleanly in diffs.
    const prefixes = opts.entries.map((e) =>
      e.detail ? `${e.name}    ${e.detail}` : e.name,
    );
    const width = Math.max(...prefixes.map((p) => p.length));
    for (let i = 0; i < opts.entries.length; i++) {
      lines.push(
        `//   ${prefixes[i].padEnd(width)}    ${opts.entries[i].hash}`,
      );
    }
  } else {
    lines.push("//   (no cached entries)");
  }

  lines.push(CLOSE_RULE);
  return `${lines.join("\n")}\n`;
}

interface ParsedCacheHeader {
  /** Version parsed from the open rule, or null if no header was found. */
  version: string | null;
  /** Generation timestamp parsed from the open rule, or null if absent. */
  timestamp: string | null;
  /** Map of entry name → hash for every parsed entry line. */
  hashes: Record<string, string>;
}

/**
 * Decide the timestamp to stamp on a freshly-rendered file, preserving the
 * committed file's timestamp when nothing changed so an all-hit regeneration is
 * byte-identical (no git churn). Returns the prior timestamp iff the file's
 * existing header carries the exact same set of entry→hash pairs; otherwise a
 * fresh `now` ISO string (a real change → new stamp).
 */
export function resolveHeaderTimestamp(
  priorSource: string,
  nextEntries: CacheHeaderEntry[],
): string {
  const prior = parseCacheHeader(priorSource);
  const now = new Date().toISOString();
  if (prior.timestamp === null) return now;
  const priorKeys = Object.keys(prior.hashes);
  if (priorKeys.length !== nextEntries.length) return now;
  for (const e of nextEntries) {
    if (prior.hashes[e.name] !== e.hash) return now;
  }
  return prior.timestamp;
}

const HEX_RE = /^[0-9a-f]+$/i;

/**
 * Parse the cache header out of a generated `.d.ts` file's contents. Returns an
 * empty result when no (or a malformed) header is present, so a missing header
 * safely reads as "every entry is a MISS".
 *
 * Robustness: an entry line is `//   <name> [<decorative...>] <hash>`. Only the
 * first token (name) and the last token (hash, validated as hex) are read; any
 * middle columns are decorative and ignored. This keeps parsing stable across
 * the differing per-subsystem line layouts.
 */
export function parseCacheHeader(source: string): ParsedCacheHeader {
  const lines = source.split("\n");
  let version: string | null = null;
  let timestamp: string | null = null;
  // Null-prototype map so an entry named "__proto__" is an own key, not a
  // prototype write (no prototype pollution from a committed file).
  const hashes: Record<string, string> = Object.create(null);

  let inTable = false;
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!inTable) {
      if (line.startsWith(OPEN_RULE_PREFIX)) {
        const m = line.match(/·\s*v([^\s·]+)/);
        version = m ? m[1] : null;
        // Timestamp is the last "· <value> ··" segment before the closing "──".
        const ts = line.match(/·\s*([0-9T:.-]+Z)\s*──\s*$/);
        timestamp = ts ? ts[1] : null;
        inTable = true;
      }
      continue;
    }
    // Inside the table: the close rule ends it.
    if (line === CLOSE_RULE) break;
    // The explainer and "(no cached entries)" lines have no trailing hex hash.
    const body = line.replace(/^\/\/\s*/, "");
    const tokens = body.split(/\s+/).filter(Boolean);
    if (tokens.length < 2) continue;
    const last = tokens[tokens.length - 1];
    if (!HEX_RE.test(last)) continue;
    const name = tokens[0];
    hashes[name] = last;
  }

  return { version, timestamp, hashes };
}

/**
 * Extract the balanced body (between the outermost `{` and its matching `}`) of
 * `interface <interfaceName> { ... }` from the source, or null if not found.
 */
function extractInterfaceBody(
  source: string,
  interfaceName: string,
): string | null {
  const marker = `interface ${interfaceName}`;
  const at = source.indexOf(marker);
  if (at === -1) return null;
  const open = source.indexOf("{", at + marker.length);
  if (open === -1) return null;
  const close = captureBalanced(source, open);
  if (close === -1) return null;
  return source.slice(open + 1, close);
}

/**
 * Split the members of a generated registry interface into a map of
 * `entryName → renderedValueBlock`, where the value block is the balanced
 * `{ ... }` object literal that follows `name:`. A cache hit reuses the entry's
 * block verbatim, so the regenerated type is identical without re-describing.
 *
 * String literals, `//` line comments, and `/* *​/` block comments are skipped
 * so braces inside them never corrupt the member boundaries. Quoted member
 * names are unquoted so the key matches the logical entry name used elsewhere.
 */
export function splitEntryBlocks(
  source: string,
  interfaceName: string,
): Record<string, string> {
  const body = extractInterfaceBody(source, interfaceName);
  if (body === null) return {};

  // Null-prototype map so a member literally named "__proto__" is stored as an
  // own key rather than hitting the prototype setter (no prototype pollution).
  const blocks: Record<string, string> = Object.create(null);
  let i = 0;
  const n = body.length;
  while (i < n) {
    i = skipTrivia(body, i);
    if (i >= n) break;

    // Read the member key: a quoted string or a bare identifier.
    const key = readKey(body, i);
    if (!key) break;
    i = key.next;

    i = skipTrivia(body, i);
    if (body[i] !== ":") break;
    i = skipTrivia(body, i + 1);

    if (body[i] !== "{") break;
    const close = captureBalanced(body, i);
    if (close === -1) break;
    blocks[key.name] = body.slice(i, close + 1);
    i = close + 1;

    // Skip an optional member separator.
    i = skipTrivia(body, i);
    if (body[i] === ";" || body[i] === ",") i += 1;
  }

  return blocks;
}

/**
 * Reverse the fixed indentation that a renderer applies to every non-first line
 * of a value block (queries indent members by 4 spaces at assembly time). Given
 * a final-form block extracted from a committed file, strip up to `n` leading
 * spaces from lines 2..N to recover the renderer's pre-indent input, so the
 * reused block re-renders byte-identically. The first line is left untouched.
 */
export function deindentBlock(block: string, n: number): string {
  const strip = new RegExp(`^ {1,${n}}`);
  return block
    .split("\n")
    .map((line, i) => (i === 0 ? line : line.replace(strip, "")))
    .join("\n");
}

/**
 * Given a `{ key: value; ... }` object-type block (including the outer braces),
 * return its top-level member key names in order. Nested objects, string
 * literals, and comments are skipped, so only the outermost members are
 * returned. Quoted keys are unquoted. Returns [] if `block` isn't an object.
 */
export function objectTopLevelKeys(block: string): string[] {
  const open = block.indexOf("{");
  if (open === -1) return [];
  const close = captureBalanced(block, open);
  if (close === -1) return [];
  const body = block.slice(open + 1, close);

  const keys: string[] = [];
  let i = 0;
  const n = body.length;
  while (i < n) {
    i = skipTrivia(body, i);
    if (i >= n) break;
    const key = readKey(body, i);
    if (!key) break;
    i = skipTrivia(body, key.next);
    if (body[i] !== ":") {
      // Not a `key:` member (e.g. an index signature or union) — bail out to
      // avoid mis-parsing; the caller treats an empty/partial list as "no
      // allowlist" (passthrough), which is safe.
      break;
    }
    keys.push(key.name);
    i = skipTrivia(body, i + 1);
    // Skip this member's value: a balanced object, or up to the next top-level
    // `;` / `,`.
    if (body[i] === "{") {
      const vClose = captureBalanced(body, i);
      if (vClose === -1) break;
      i = vClose + 1;
    } else {
      i = skipToTopLevelSeparator(body, i);
    }
    i = skipTrivia(body, i);
    if (body[i] === ";" || body[i] === ",") i += 1;
  }
  return keys;
}

/**
 * From a `{ member: <value>; ... }` object-type block, return the raw text of
 * `<value>` for the named top-level member, or undefined if absent. The value
 * runs from just after `member:` to (but not including) its top-level `;`/`,`.
 */
export function objectMemberValue(
  block: string,
  member: string,
): string | undefined {
  const open = block.indexOf("{");
  if (open === -1) return undefined;
  const close = captureBalanced(block, open);
  if (close === -1) return undefined;
  const body = block.slice(open + 1, close);

  let i = 0;
  const n = body.length;
  while (i < n) {
    i = skipTrivia(body, i);
    if (i >= n) break;
    const key = readKey(body, i);
    if (!key) break;
    i = skipTrivia(body, key.next);
    if (body[i] !== ":") break;
    i = skipTrivia(body, i + 1);
    const valueStart = i;
    if (body[i] === "{") {
      const vClose = captureBalanced(body, i);
      if (vClose === -1) break;
      i = vClose + 1;
    } else {
      i = skipToTopLevelSeparator(body, i);
    }
    if (key.name === member) {
      return body.slice(valueStart, i).trim();
    }
    i = skipTrivia(body, i);
    if (body[i] === ";" || body[i] === ",") i += 1;
  }
  return undefined;
}

/**
 * Advance past a member value that is not a brace-object, stopping at the next
 * top-level `;` or `,`. Skips nested `<...>`, `(...)`, `[...]`, `{...}`, strings
 * and comments so separators inside them don't end the value early.
 */
function skipToTopLevelSeparator(source: string, i: number): number {
  const n = source.length;
  let angle = 0;
  while (i < n) {
    const c = source[i];
    if (c === '"' || c === "'" || c === "`") {
      i = skipString(source, i);
      continue;
    }
    if (c === "/" && source[i + 1] === "/") {
      i = skipLineComment(source, i);
      continue;
    }
    if (c === "/" && source[i + 1] === "*") {
      i = skipBlockComment(source, i);
      continue;
    }
    if (c === "{" || c === "(" || c === "[") {
      i = captureBalancedGeneric(source, i);
      continue;
    }
    if (c === "<") angle += 1;
    else if (c === ">") {
      if (angle > 0) angle -= 1;
    } else if (angle === 0 && (c === ";" || c === ",")) {
      return i;
    }
    i += 1;
  }
  return n;
}

/**
 * Like {@link captureBalanced} but for any of `{}`, `()`, `[]`; returns the
 * index just past the matching close (or end of input).
 */
function captureBalancedGeneric(source: string, open: number): number {
  const closeOf: Record<string, string> = { "{": "}", "(": ")", "[": "]" };
  const want = closeOf[source[open]];
  let depth = 0;
  let i = open;
  const n = source.length;
  while (i < n) {
    const c = source[i];
    if (c === '"' || c === "'" || c === "`") {
      i = skipString(source, i);
      continue;
    }
    if (c === "/" && source[i + 1] === "/") {
      i = skipLineComment(source, i);
      continue;
    }
    if (c === "/" && source[i + 1] === "*") {
      i = skipBlockComment(source, i);
      continue;
    }
    if (c === source[open]) depth += 1;
    else if (c === want) {
      depth -= 1;
      if (depth === 0) return i + 1;
    }
    i += 1;
  }
  return n;
}

// ── low-level scanners ─────────────────────────────────────────────────────

/**
 * Given `source[open] === "{"`, return the index of the matching `}` (or -1).
 * Skips string literals (", ', `) and `//` / block comments so their contents
 * cannot throw off the brace depth.
 */
function captureBalanced(source: string, open: number): number {
  let depth = 0;
  let i = open;
  const n = source.length;
  while (i < n) {
    const c = source[i];
    if (c === '"' || c === "'" || c === "`") {
      i = skipString(source, i);
      continue;
    }
    if (c === "/" && source[i + 1] === "/") {
      i = skipLineComment(source, i);
      continue;
    }
    if (c === "/" && source[i + 1] === "*") {
      i = skipBlockComment(source, i);
      continue;
    }
    if (c === "{") depth += 1;
    else if (c === "}") {
      depth -= 1;
      if (depth === 0) return i;
    }
    i += 1;
  }
  return -1;
}

/** Skip whitespace and both comment styles, returning the next content index. */
function skipTrivia(source: string, i: number): number {
  const n = source.length;
  while (i < n) {
    const c = source[i];
    if (c === " " || c === "\t" || c === "\n" || c === "\r") {
      i += 1;
    } else if (c === "/" && source[i + 1] === "/") {
      i = skipLineComment(source, i);
    } else if (c === "/" && source[i + 1] === "*") {
      i = skipBlockComment(source, i);
    } else {
      break;
    }
  }
  return i;
}

/** `source[i]` is a quote char; return the index just past the closing quote. */
function skipString(source: string, i: number): number {
  const quote = source[i];
  i += 1;
  const n = source.length;
  while (i < n) {
    const c = source[i];
    if (c === "\\") {
      i += 2;
      continue;
    }
    if (c === quote) return i + 1;
    i += 1;
  }
  return n;
}

/** `source[i]` starts a `//` comment; return the index of the newline/EOF. */
function skipLineComment(source: string, i: number): number {
  const nl = source.indexOf("\n", i);
  return nl === -1 ? source.length : nl;
}

/** `source[i]` starts a block comment; return the index just past its close. */
function skipBlockComment(source: string, i: number): number {
  const end = source.indexOf("*/", i + 2);
  return end === -1 ? source.length : end + 2;
}

/** Read a member key (quoted string or bare identifier) at `source[i]`. */
function readKey(
  source: string,
  i: number,
): { name: string; next: number } | null {
  const c = source[i];
  if (c === '"' || c === "'") {
    const end = skipString(source, i);
    // Strip the surrounding quotes to recover the logical name.
    return { name: source.slice(i + 1, end - 1), next: end };
  }
  const m = /^[A-Za-z0-9_$]+/.exec(source.slice(i));
  if (!m) return null;
  return { name: m[0], next: i + m[0].length };
}

// ── package version resolution ───────────────────────────────────────────

let cachedVersion: string | undefined;

/**
 * Resolve the installed `@databricks/appkit` version for the header stamp.
 * Walks up from this module looking for the package's own package.json;
 * returns "unknown" if it can't be found (never throws).
 */
function getAppkitVersion(): string {
  if (cachedVersion !== undefined) return cachedVersion;
  cachedVersion = "unknown";
  try {
    let dir = path.dirname(fileURLToPath(import.meta.url));
    for (let depth = 0; depth < 8; depth++) {
      const pkgPath = path.join(dir, "package.json");
      if (fsSync.existsSync(pkgPath)) {
        const pkg = JSON.parse(fsSync.readFileSync(pkgPath, "utf8")) as {
          name?: string;
          version?: string;
        };
        if (pkg.name === "@databricks/appkit" && pkg.version) {
          cachedVersion = pkg.version;
          break;
        }
      }
      const parent = path.dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  } catch {
    // Fall back to "unknown" — the version stamp is informational only.
  }
  return cachedVersion;
}
