import fs from "node:fs/promises";
import path from "node:path";
import dotenv from "dotenv";
import { createLogger } from "../logging/logger";
import {
  createWorkspaceDescribeFetcher,
  type DescribeFetcher,
  generateMetricTypeDeclarations,
  type MetricSchema,
  readMetricConfig,
  resolveMetricConfig,
  syncMetrics,
} from "./metric-registry";
import {
  migrateProjectConfig,
  removeOldGeneratedTypes,
  resolveProjectRoot,
} from "./migration";
import { generateQueriesFromDescribe } from "./query-registry";
import { generateServingTypes as generateServingTypesImpl } from "./serving/generator";
import type { QuerySchema } from "./types";

dotenv.config();

const logger = createLogger("type-generator");

/**
 * Generate type declarations for QueryRegistry
 * Create the d.ts file from the plugin routes and query schemas
 * @param querySchemas - the list of query schemas
 * @returns - the type declarations as a string
 */
function generateTypeDeclarations(querySchemas: QuerySchema[] = []): string {
  const queryEntries = querySchemas
    .map(({ name, type }) => {
      const indentedType = type
        .split("\n")
        .map((line, i) => (i === 0 ? line : `    ${line}`))
        .join("\n");
      return `    ${name}: ${indentedType}`;
    })
    .join(";\n");

  const querySection = queryEntries ? `\n${queryEntries};\n  ` : "";

  return `// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {${querySection}}
}
`;
}

/**
 * Entry point for generating type declarations from all imported files
 * @param options - the options for the generation
 * @param options.entryPoint - the entry point file
 * @param options.outFile - the output file
 * @param options.metricOutFile - optional output file for the MetricRegistry
 *   augmentation. Defaults to a sibling `metric.d.ts` file under the same
 *   directory as `outFile`. Skipped entirely if `metric.json` is absent.
 * @param options.metricFetcher - optional DescribeFetcher used by
 *   {@link syncMetrics}. Tests inject a mock; production builds let the
 *   default WorkspaceClient-backed fetcher be created lazily.
 */
export async function generateFromEntryPoint(options: {
  outFile: string;
  queryFolder?: string;
  warehouseId: string;
  noCache?: boolean;
  metricOutFile?: string;
  metricFetcher?: DescribeFetcher;
}) {
  const {
    outFile,
    queryFolder,
    warehouseId,
    noCache,
    metricOutFile,
    metricFetcher,
  } = options;
  const projectRoot = resolveProjectRoot(outFile);

  logger.debug("Starting type generation...");

  let queryRegistry: QuerySchema[] = [];
  if (queryFolder)
    queryRegistry = await generateQueriesFromDescribe(
      queryFolder,
      warehouseId,
      {
        noCache,
      },
    );

  const failedQueries = queryRegistry.filter((q) =>
    q.type.includes("result: unknown"),
  );
  if (failedQueries.length > 0) {
    const names = failedQueries.map((q) => q.name).join(", ");
    throw new Error(
      [
        `Type generation failed: ${failedQueries.length} ${failedQueries.length === 1 ? "query" : "queries"} could not be described: ${names}.`,
        `DESCRIBE QUERY failed for these queries — see the error codes above for details.`,
        `Common causes: SQL syntax errors, missing tables/views, or warehouse format incompatibilities.`,
        `To debug: run the failing query directly in a SQL editor against warehouse ${warehouseId}.`,
      ].join("\n"),
    );
  }

  const typeDeclarations = generateTypeDeclarations(queryRegistry);

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, typeDeclarations, "utf-8");

  // Metric-view types: only emit when metric.json exists. The path is purely
  // additive — apps that never adopt metric views must not produce empty noise.
  if (queryFolder) {
    const metricConfig = await readMetricConfig(queryFolder);
    if (metricConfig) {
      const resolution = resolveMetricConfig(metricConfig);
      const fetcher =
        metricFetcher ?? createWorkspaceDescribeFetcher(warehouseId);
      const metricSchemas: MetricSchema[] = await syncMetrics(
        resolution,
        fetcher,
      );

      const metricFile =
        metricOutFile ?? path.join(path.dirname(outFile), METRIC_TYPES_FILE);
      const metricDeclarations = generateMetricTypeDeclarations(metricSchemas);
      await fs.mkdir(path.dirname(metricFile), { recursive: true });
      await fs.writeFile(metricFile, metricDeclarations, "utf-8");
      logger.debug(
        "Wrote MetricRegistry augmentation for %d metric(s)",
        metricSchemas.length,
      );
    }
  }

  // One-time migration: remove old generated file and patch project configs
  await removeOldGeneratedTypes(projectRoot, "appKitTypes.d.ts");
  await migrateProjectConfig(projectRoot);

  logger.debug("Type generation complete!");
}

// Rolldown tree-shaking only preserves "own exports" (locally defined) — not re-exports.
// A local binding ensures the serving vite plugin's import keeps this in the dependency graph,
// mirroring how generateFromEntryPoint (also defined here) is preserved via the analytics vite plugin.
export const generateServingTypes = generateServingTypesImpl;

/** Directory name for generated AppKit type declaration files. */
export const TYPES_DIR = "appkit-types";
/** Default filename for analytics query type declarations. */
export const ANALYTICS_TYPES_FILE = "analytics.d.ts";
/** Default filename for serving endpoint type declarations. */
export const SERVING_TYPES_FILE = "serving.d.ts";
/** Default filename for metric-view registry type declarations. */
export const METRIC_TYPES_FILE = "metric.d.ts";
