import fs from "node:fs/promises";
import dotenv from "dotenv";
import { createLogger } from "../logging/logger";
import { generateQueriesFromDescribe } from "./query-registry";
import { generateServingTypes as generateServingTypesImpl } from "./serving/generator";
import type { QuerySchema } from "./types";

dotenv.config();

const logger = createLogger("type-generator");

/**
 * Generate type declarations for QueryRegistry
 * Create the d.ts file from the plugin routes and query schemas
 * @param querySchemas - the list of query schemas
 * @returns - the type declarations as a string
 */
function generateTypeDeclarations(querySchemas: QuerySchema[] = []): string {
  const queryEntries = querySchemas
    .map(({ name, type }) => {
      const indentedType = type
        .split("\n")
        .map((line, i) => (i === 0 ? line : `    ${line}`))
        .join("\n");
      return `    ${name}: ${indentedType}`;
    })
    .join(";\n");

  const querySection = queryEntries ? `\n${queryEntries};\n  ` : "";

  return `// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {${querySection}}
}
`;
}

/**
 * Entry point for generating type declarations from all imported files
 * @param options - the options for the generation
 * @param options.entryPoint - the entry point file
 * @param options.outFile - the output file
 * @param options.querySchemaFile - optional path to query schema file (e.g. config/queries/schema.ts)
 */
export async function generateFromEntryPoint(options: {
  outFile: string;
  queryFolder?: string;
  warehouseId: string;
  noCache?: boolean;
}) {
  const { outFile, queryFolder, warehouseId, noCache } = options;

  logger.debug("Starting type generation...");

  let queryRegistry: QuerySchema[] = [];
  if (queryFolder)
    queryRegistry = await generateQueriesFromDescribe(
      queryFolder,
      warehouseId,
      {
        noCache,
      },
    );

  const failedQueries = queryRegistry.filter((q) =>
    q.type.includes("result: unknown"),
  );
  if (failedQueries.length > 0) {
    const names = failedQueries.map((q) => q.name).join(", ");
    throw new Error(
      [
        `Type generation failed: ${failedQueries.length} ${failedQueries.length === 1 ? "query" : "queries"} could not be described: ${names}.`,
        `DESCRIBE QUERY failed for these queries — see the error codes above for details.`,
        `Common causes: SQL syntax errors, missing tables/views, or warehouse format incompatibilities.`,
        `To debug: run the failing query directly in a SQL editor against warehouse ${warehouseId}.`,
      ].join("\n"),
    );
  }

  const typeDeclarations = generateTypeDeclarations(queryRegistry);

  await fs.writeFile(outFile, typeDeclarations, "utf-8");

  logger.debug("Type generation complete!");
}

// Rolldown tree-shaking only preserves "own exports" (locally defined) — not re-exports.
// A local binding ensures the serving vite plugin's import keeps this in the dependency graph,
// mirroring how generateFromEntryPoint (also defined here) is preserved via the analytics vite plugin.
export const generateServingTypes = generateServingTypesImpl;
