import type { BasePluginConfig } from "shared";

export interface EndpointConfig {
  /** Environment variable holding the endpoint name. */
  env: string;
  /** Target a specific served model (bypasses traffic routing). */
  servedModel?: string;
}

export interface IServingConfig extends BasePluginConfig {
  /** Map of alias → endpoint config. Defaults to { default: { env: "DATABRICKS_SERVING_ENDPOINT_NAME" } } if omitted. */
  endpoints?: Record<string, EndpointConfig>;
  /** Request timeout in ms. Default: 120000 (2 min) */
  timeout?: number;
  /** How to handle unknown request parameters. 'strip' silently removes them (default). 'reject' returns 400. */
  filterMode?: "strip" | "reject";
}

/**
 * Registry interface for serving endpoint type generation.
 * Empty by default — augmented by the Vite type generator's `.d.ts` output via module augmentation.
 * When populated, provides autocomplete for alias names and typed request/response/chunk per endpoint.
 */
// biome-ignore lint/suspicious/noEmptyInterface: intentionally empty — populated via module augmentation
export interface ServingEndpointRegistry {}

/** Shape of a single registry entry. */
export interface ServingEndpointEntry {
  request: Record<string, unknown>;
  response: unknown;
  chunk: unknown;
}

/** Typed invoke method for a serving endpoint. */
export interface ServingEndpointMethods<
  TRequest extends Record<string, unknown> = Record<string, unknown>,
  TResponse = unknown,
> {
  invoke: (body: TRequest) => Promise<TResponse>;
}

/** Endpoint handle with asUser support, returned by the exports factory. */
export type ServingEndpointHandle<
  TRequest extends Record<string, unknown> = Record<string, unknown>,
  TResponse = unknown,
> = ServingEndpointMethods<TRequest, TResponse> & {
  asUser: (
    req: import("express").Request,
  ) => ServingEndpointMethods<TRequest, TResponse>;
};

/**
 * Factory function returned by `AppKit.serving`.
 *
 * This is a conditional type that adapts based on whether `ServingEndpointRegistry`
 * has been populated via module augmentation (generated by `appKitServingTypesPlugin()`):
 *
 * - **Registry empty (default):** `(alias?: string) => ServingEndpointHandle` —
 *   accepts any alias string with untyped request/response.
 * - **Registry populated:** `<K>(alias: K) => ServingEndpointHandle<...>` —
 *   restricts `alias` to known endpoint keys and infers typed request/response
 *   from the registry entry.
 *
 * Run `appKitServingTypesPlugin()` in your Vite config to generate the registry
 * augmentation and enable full type safety.
 */
export type ServingFactory = keyof ServingEndpointRegistry extends never
  ? (alias?: string) => ServingEndpointHandle
  : <K extends keyof ServingEndpointRegistry>(
      alias: K,
    ) => ServingEndpointHandle<
      ServingEndpointRegistry[K]["request"],
      ServingEndpointRegistry[K]["response"]
    >;
