import fs from "node:fs";
import path from "node:path";

/**
 * Harness binaries with their own shell run through a bubblewrap wrapper, so
 * the shell cannot read the app's state or other processes' memory:
 *
 * - own PID, IPC and UTS namespaces;
 * - the runtime directory masked with a tmpfs, with only this user's home and
 *   work directory (and the public `bin` directory) bound back in;
 * - `/proc/<pid>` of every protected process (Node, the Omnigent server, the
 *   hosts) overmounted, since Apps containers cannot mount a fresh procfs.
 *
 * The protected list is read at launch, so a process started later is not
 * masked from a harness that is already running; the plugin keeps secrets out
 * of every child's environment so such a process has nothing to leak.
 */
export class HarnessSandbox {
  private readonly pidFile: string;

  constructor(
    private readonly root: string,
    private readonly bwrap: string,
  ) {
    this.pidFile = path.join(root, "protected.pids");
  }

  get publicBin(): string {
    return path.join(this.root, "bin");
  }

  /** Records the processes sandboxed harnesses must not see. */
  protect(pids: Array<number | undefined>): void {
    const list = [
      ...new Set(pids.filter((p): p is number => typeof p === "number")),
    ];
    fs.writeFileSync(this.pidFile, `${list.join("\n")}\n`);
  }

  /** Directory of wrappers named after the real CLIs; must come first on the hosts' PATH. */
  get shimDir(): string {
    return path.join(this.publicBin, "sandboxed");
  }

  /**
   * Writes a wrapper named like the CLI it wraps (`codex`) and returns its
   * path. Omnigent may launch a harness by `OMNIGENT_*_PATH` or by name from
   * `PATH`, so both must resolve to the wrapper: put {@link shimDir} first on
   * `PATH`.
   */
  wrap(name: string, real: string): string {
    fs.mkdirSync(this.shimDir, { recursive: true });
    const wrapper = path.join(this.shimDir, name);
    fs.writeFileSync(wrapper, this.script(real), { mode: 0o755 });
    return wrapper;
  }

  script(real: string): string {
    const q = shellQuote;
    return `#!/bin/sh
# Generated by the AppKit omnigent plugin. $HOME is <root>/users/<id>/home.
U="$(dirname "$HOME")"
W=${q(path.join(this.root, "work"))}/"$(basename "$U")"
MASK=""
for p in $(cat ${q(this.pidFile)} 2>/dev/null); do
  [ -d "/proc/$p" ] && MASK="$MASK --tmpfs /proc/$p"
done
exec ${q(this.bwrap)} --die-with-parent --unshare-pid --unshare-ipc --unshare-uts \\
  --dev-bind / / --tmpfs ${q(this.root)} $MASK \\
  --bind "$U" "$U" --bind "$W" "$W" --ro-bind ${q(this.publicBin)} ${q(this.publicBin)} \\
  -- ${q(real)} "$@"
`;
  }
}

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}
