import fs from "node:fs";
import dotenv from "dotenv";
import { generateQueriesFromDescribe } from "./query-registry";
import type { QuerySchema } from "./types";

dotenv.config();

/**
 * Generate type declarations for QueryRegistry
 * Create the d.ts file from the plugin routes and query schemas
 * @param querySchemas - the list of query schemas
 * @returns - the type declarations as a string
 */
function generateTypeDeclarations(querySchemas: QuerySchema[] = []): string {
  const queryEntries = querySchemas
    .map(({ name, type }) => {
      const indentedType = type
        .split("\n")
        .map((line, i) => (i === 0 ? line : `    ${line}`))
        .join("\n");
      return `    ${name}: ${indentedType}`;
    })
    .join(";\n");

  const querySection = queryEntries ? `\n${queryEntries};\n  ` : "";

  return `// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx appkit-generate-types' or Vite plugin during build
import "@databricks/app-kit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/app-kit-ui/js";

declare module "@databricks/app-kit-ui/react" {
  interface QueryRegistry {${querySection}}
}
`;
}

/**
 * Entry point for generating type declarations from all imported files
 * @param options - the options for the generation
 * @param options.entryPoint - the entry point file
 * @param options.outFile - the output file
 * @param options.querySchemaFile - optional path to query schema file (e.g. config/queries/schema.ts)
 */
export async function generateFromEntryPoint(options: {
  outFile: string;
  queryFolder?: string;
  warehouseId: string;
  noCache?: boolean;
}) {
  const { outFile, queryFolder, warehouseId, noCache } = options;

  console.log("\n[AppKit] Starting type generation...\n");

  let queryRegistry: QuerySchema[] = [];
  if (queryFolder)
    queryRegistry = await generateQueriesFromDescribe(
      queryFolder,
      warehouseId,
      {
        noCache,
      },
    );

  const typeDeclarations = generateTypeDeclarations(queryRegistry);

  fs.writeFileSync(outFile, typeDeclarations, "utf-8");

  console.log("\n[AppKit] Type generation complete!\n");
}
