import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@databricks/appkit-ui/react";
import { createFileRoute, retainSearchParams } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { codeToHtml } from "shiki";
import {
  BoardExplorer,
  HookLifecycle,
  RefusalProbe,
} from "@/components/database";
import { Header } from "@/components/layout/header";

export const Route = createFileRoute("/database")({
  component: DatabaseRoute,
  search: {
    middlewares: [retainSearchParams(true)],
  },
});

function CodeBlock({
  code,
  lang = "typescript",
}: {
  code: string;
  lang?: string;
}) {
  const [html, setHtml] = useState("");

  useEffect(() => {
    codeToHtml(code, { lang, theme: "dark-plus" }).then(setHtml);
  }, [code, lang]);

  return (
    <div
      className="rounded-md overflow-hidden [&>pre]:m-0 [&>pre]:p-4 [&>pre]:text-sm [&>pre]:overflow-x-auto font-mono"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

const SCHEMA_EXAMPLE = `// config/database/schema.ts
export const schema = defineSchema(({ table }) => {
  const boards = table("boards", {
    id: id(),
    slug: varchar(64).notNull().unique(),
    title: text().notNull(),
    created_at: timestamp({ withTimezone: true })
      .defaultNow()
      .notNull(),
  });

  const notes = table("notes", {
    id: id(),
    board_id: fk(() => boards.id)
      .notNull()
      .onDelete("cascade"),
    author: text().notNull(),
    // The server needs it; no client should see it.
    author_email: text().private(),
    body: text().notNull(),
    created_at: timestamp({ withTimezone: true })
      .defaultNow()
      .notNull(),
  });

  const note_events = table("note_events", {
    id: id(),
    note_id: fk(() => notes.id)
      .notNull()
      .onDelete("cascade"),
    action: varchar(32).notNull(),
    created_at: timestamp({ withTimezone: true })
      .defaultNow()
      .notNull(),
  });

  return { boards, notes, note_events };
});`;

const GENERATED_TYPES = `// shared/appkit-types/database.d.ts
// Auto-generated by AppKit - DO NOT EDIT
declare module "@databricks/appkit" {
  interface DatabaseRegistry {
    "notes": {
      // What server code sees.
      row: {
        id: number;
        board_id: number;
        author: string;
        author_email: string | null;
        body: string;
        created_at: string;
      };
      // What a response can hold. Not a convention:
      // a handler returning the private column
      // does not typecheck.
      publicRow: {
        id: number;
        board_id: number;
        author: string;
        body: string;
        created_at: string;
      };
      insert: { board_id: number; /* ... */ };
      update: { board_id?: number; /* ... */ };
      filters: DatabaseLogicalFilter<{ /* ... */ }>;
      // A foreign key is a relation on both sides.
      includes: {
        "boards": { to: "boards"; many: false };
        "note_events": {
          to: "note_events";
          many: true;
        };
      };
      hasPrimaryKey: true;
    };
    // ... boards, note_events
  }
}`;

const REGISTRATION = `// server/index.ts
database({
  schema,
  // Only these two get HTTP routes. note_events stays server-only.
  crudRoutes: { tables: ["boards", "notes"] },
  hooks: { /* see below */ },
})`;

const HOOKS_EXAMPLE = `hooks: {
  notes: {
    // Refused on the wire, writable here.
    beforeCreate: (values) => ({
      ...values,
      author_email: \`\${values.author}@example.com\`,
    }),

    // Its write joins the same transaction, so a note
    // and its event are never out of step.
    afterCreate: async (row, ctx) => {
      await ctx.app.database.note_events.create({
        note_id: row.id,
        action: "created",
      });
    },

    // After commit, on the already-public row.
    serialize: (row, { operation }) =>
      operation === "list"
        ? { ...row, body: String(row.body).slice(0, 120) }
        : row,
  },
}`;

const PRIVATE_COLUMN = `const notes = table("notes", {
  // ...
  author: text().notNull(),
  author_email: text().private(),
});

// Server-side, it is an ordinary column.
const note = await db.notes.find(id);       // note.author_email — typed
await db.notes.create({ author_email });     // accepted

// Over HTTP, the same declaration removes it from every surface:
// the select list, where, the create body, and the update body.`;

const AGENT_SEAM = `// An agent is a definition, not a service to look up, so a
// hook runs one by importing it. This is the agent that ran on
// the note you just wrote.
const redactor = createAgent({
  instructions: "Replace every personal name and email with [redacted].",
});

hooks: {
  notes: {
    // Atomic with the row: the unredacted body must never reach the
    // table, so this has to happen before the insert, not after it.
    // It holds a transaction open — give it a timeout.
    beforeCreate: async (values) => {
      const answer = await runAgent(redactor, { messages: values.body });
      return { ...values, body: answer.text };
    },

    // The row exists, and this write still shares its transaction, so a
    // failure here takes the note with it. Good for derived rows; wrong
    // for best-effort work like sending mail.
    afterCreate: async (row, ctx) => {
      await ctx.app.database.note_events.create({
        note_id: row.id,
        action: "created",
      });
    },

    // Not a candidate: no await is possible here. Anything a model
    // produced has to already be a column by the time a read runs.
    serialize: (row) => row,
  },
}`;

const CUSTOM_ROUTES = `// The generated routes shape rows; they do not group them,
// and they stop at the exposure list. Everything else is yours.
app.get("/api/boards/stats", async (_req, res) => {
  const rows = await db.sql<{ slug: string; notes: string }>\`
    select b.slug, count(n.id)::text as notes
    from boards b left join notes n on n.board_id = b.id
    group by b.slug order by b.slug
  \`;
  res.json(rows);
});

// Two bounded relation edges, including a table with no route of its own.
const board = await db.boards
  .where({ slug: req.params.slug })
  .include({ notes: { limit: 20, include: { note_events: { limit: 5 } } } })
  .first();`;

/** The five routes the plugin writes for every table named in `crudRoutes`. */
const GENERATED_ROUTES = [
  {
    method: "GET",
    suffix: "",
    purpose: "List with filters, order, pagination and includes",
  },
  { method: "GET", suffix: "/:id", purpose: "One row by primary key" },
  {
    method: "POST",
    suffix: "",
    purpose: "Create, with before/after hooks in one transaction",
  },
  {
    method: "PATCH",
    suffix: "/:id",
    purpose: "Partial update against the generated update schema",
  },
  {
    method: "DELETE",
    suffix: "/:id",
    purpose: "Delete one row, with the same hooks available",
  },
] as const;

const METHOD_TONE: Record<string, string> = {
  GET: "text-emerald-600 dark:text-emerald-400",
  POST: "text-blue-600 dark:text-blue-400",
  PATCH: "text-amber-600 dark:text-amber-400",
  DELETE: "text-red-600 dark:text-red-400",
};

function RouteTable() {
  return (
    <div className="space-y-6">
      {["boards", "notes"].map((table) => (
        <div key={table}>
          <div className="flex items-center gap-2 mb-2">
            <code className="text-sm font-semibold">{table}</code>
            <Badge variant="secondary">exposed</Badge>
          </div>
          <div className="rounded-md border divide-y">
            {GENERATED_ROUTES.map((route) => (
              <div
                key={`${route.method}${route.suffix}`}
                className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-4 px-3 py-2"
              >
                <code
                  className={`text-xs font-bold w-16 shrink-0 ${METHOD_TONE[route.method]}`}
                >
                  {route.method}
                </code>
                <code className="text-xs sm:w-72 shrink-0">
                  /api/database/{table}
                  {route.suffix}
                </code>
                <span className="text-xs text-muted-foreground">
                  {route.purpose}
                </span>
              </div>
            ))}
          </div>
        </div>
      ))}

      <div>
        <div className="flex items-center gap-2 mb-2">
          <code className="text-sm font-semibold">note_events</code>
          <Badge variant="outline">not exposed</Badge>
        </div>
        <div className="rounded-md border border-dashed px-3 py-3 text-xs text-muted-foreground">
          No routes at all. The table is still fully typed for server code, and
          a hook writes to it on every note — it is simply unreachable from a
          browser, including as an <code>include</code> on a table that is
          exposed.
        </div>
      </div>
    </div>
  );
}

function DatabaseRoute() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-6xl mx-auto px-6 py-12">
        <Header
          title="Database"
          description="Declare a Postgres schema once and get typed entities, generated CRUD routes, and transactional hooks — without writing a controller."
          tooltip="The DatabasePlugin reads an explicit schema. It never creates, migrates, or introspects tables."
        />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Live</CardTitle>
              <CardDescription>
                Boards, their notes, and the audit trail a hook keeps for them.
                Every request below hits a route this app never wrote.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <BoardExplorer />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>1. Declare the schema</CardTitle>
              <CardDescription>
                Columns and foreign keys in TypeScript. The plugin expects these
                tables to already exist — it owns no migrations.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CodeBlock code={SCHEMA_EXAMPLE} />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>2. Types follow</CardTitle>
              <CardDescription>
                <code className="text-xs">appkit generate-types</code> turns the
                schema into a registry augmentation, so rows, filters, and
                includes are checked at compile time.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CodeBlock code={GENERATED_TYPES} />
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>
                3. Routes are generated from the exposure list
              </CardTitle>
              <CardDescription>
                A declared table is a server-side capability. It becomes a
                network surface only where the registration says so.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="rounded-md border-l-4 border-l-primary bg-muted/40 px-4 py-3">
                <p className="text-sm font-medium">
                  Nothing is exposed by default.
                </p>
                <p className="text-sm text-muted-foreground mt-1">
                  Drop <code>crudRoutes</code> and this app has a fully typed
                  database and zero database endpoints. Every table stays
                  reachable from your own routes and hooks, and from nowhere
                  else. Exposure is a list you write, one table at a time — not
                  something you remember to switch off.
                </p>
              </div>
              <CodeBlock code={REGISTRATION} />
              <RouteTable />
              <div className="space-y-2">
                <p className="text-sm font-medium">
                  Ask the running server for a table it does not publish
                </p>
                <RefusalProbe
                  label="Reach note_events through a relation on an exposed table"
                  request={`GET /api/database/boards?include={"note_events":true}`}
                  send={() =>
                    fetch(
                      `/api/database/boards?include=${encodeURIComponent(
                        JSON.stringify({ note_events: true }),
                      )}`,
                    )
                  }
                />
              </div>
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Private columns</CardTitle>
              <CardDescription>
                <code className="text-xs">private()</code> marks a column the
                server owns. It is the same declaration that keeps it out of
                four separate request surfaces.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <CodeBlock code={PRIVATE_COLUMN} />
              <p className="text-sm text-muted-foreground">
                A private column is dropped from the select list before the
                query is built, so it never leaves Postgres; it is refused in{" "}
                <code>where</code>, so nobody can guess it a character at a
                time; it is refused in write bodies rather than quietly ignored;
                and it is stripped on the way out even if a serializer puts it
                back. Server code, meanwhile, reads and writes it normally —
                which is how <code>author_email</code> gets set at all.
              </p>
              <div className="space-y-2">
                <RefusalProbe
                  label="Read it"
                  request="GET /api/database/notes — author_email is simply absent"
                  send={() => fetch("/api/database/notes?limit=1")}
                />
                <RefusalProbe
                  label="Filter by it"
                  request={`GET /api/database/notes?where={"author_email":"victor@example.com"}`}
                  send={() =>
                    fetch(
                      `/api/database/notes?where=${encodeURIComponent(
                        JSON.stringify({ author_email: "victor@example.com" }),
                      )}`,
                    )
                  }
                />
                <RefusalProbe
                  label="Write it"
                  request={`POST /api/database/notes with "author_email"`}
                  send={() =>
                    fetch("/api/database/notes", {
                      method: "POST",
                      headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({
                        board_id: 1,
                        author: "intruder",
                        body: "trying to set a private column",
                        author_email: "intruder@example.com",
                      }),
                    })
                  }
                />
              </div>
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>The lifecycle of one write</CardTitle>
              <CardDescription>
                Where your code runs, and what it is allowed to do there. This
                is the flow the panel at the top of the page executes.
              </CardDescription>
            </CardHeader>
            <CardContent className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <HookLifecycle />
              <CodeBlock code={HOOKS_EXAMPLE} />
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Running an agent from a write</CardTitle>
              <CardDescription>
                The lifecycle above decides where a model call fits: two steps
                can await one, and one cannot.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <CodeBlock code={AGENT_SEAM} />
              <p className="text-sm text-muted-foreground">
                A hook needs nothing from the plugin system to do this.{" "}
                <code>createAgent</code> returns a definition, so the hook
                imports it and calls <code>runAgent</code> — the note you added
                above went through exactly this. What the hook does need from{" "}
                <code>ctx</code> is <code>ctx.app.database</code>, because that
                one is bound to this transaction and cannot be imported. The
                model call is not: it holds a Postgres connection and the row's
                locks for as long as it runs, and nothing it did is undone if
                the transaction later rolls back. Redaction that must be atomic
                with the row belongs in <code>beforeCreate</code> under a
                timeout; a summary that can arrive a second later belongs after
                the response, keyed by the row you just wrote.
              </p>
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Where the generator stops</CardTitle>
              <CardDescription>
                Aggregates and deeper traversals stay ordinary application code,
                written against the same typed client.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CodeBlock code={CUSTOM_ROUTES} />
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
