import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@databricks/appkit-ui/react";
import { createFileRoute, retainSearchParams } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { codeToHtml } from "shiki";

import {
  BoardExplorer,
  HookLifecycle,
  RefusalProbe,
} from "@/components/database";
import { Header } from "@/components/layout/header";

export const Route = createFileRoute("/database")({
  component: DatabaseRoute,
  search: {
    middlewares: [retainSearchParams(true)],
  },
});

function CodeBlock({
  code,
  lang = "typescript",
}: {
  code: string;
  lang?: string;
}) {
  const [html, setHtml] = useState("");

  useEffect(() => {
    codeToHtml(code, { lang, theme: "dark-plus" }).then(setHtml);
  }, [code, lang]);

  return (
    <div
      className="rounded-md overflow-hidden [&>pre]:m-0 [&>pre]:p-4 [&>pre]:text-sm [&>pre]:overflow-x-auto font-mono"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

const SCHEMA_EXAMPLE = `// config/database/schema.ts
export const schema = defineSchema(({ table }) => {
  const boards = table("boards", {
    id: id(),
    slug: varchar(64).notNull().unique(),
    title: text().notNull(),
    created_at: timestamp({ withTimezone: true })
      .defaultNow()
      .notNull(),
  });

  const notes = table("notes", {
    id: id(),
    board_id: fk(() => boards.id)
      .notNull()
      .onDelete("cascade"),
    author: text().notNull(),
    // The server needs it; no client should see it.
    author_email: text().private(),
    body: text().notNull(),
    created_at: timestamp({ withTimezone: true })
      .defaultNow()
      .notNull(),
  });

  const note_events = table("note_events", {
    id: id(),
    note_id: fk(() => notes.id)
      .notNull()
      .onDelete("cascade"),
    action: varchar(32).notNull(),
    created_at: timestamp({ withTimezone: true })
      .defaultNow()
      .notNull(),
  });

  return { boards, notes, note_events };
});`;

const GENERATED_TYPES = `// shared/appkit-types/database.d.ts
// Auto-generated by AppKit - DO NOT EDIT
declare module "@databricks/appkit" {
  interface DatabaseRegistry {
    "notes": {
      // What server code sees.
      row: {
        id: number;
        board_id: number;
        author: string;
        author_email: string | null;
        body: string;
        created_at: string;
      };
      // What a response can hold. Not a convention:
      // a handler returning the private column
      // does not typecheck.
      publicRow: {
        id: number;
        board_id: number;
        author: string;
        body: string;
        created_at: string;
      };
      insert: { board_id: number; /* ... */ };
      update: { board_id?: number; /* ... */ };
      filters: DatabaseLogicalFilter<{ /* ... */ }>;
      // A foreign key is a relation on both sides.
      includes: {
        "boards": { to: "boards"; many: false };
        "note_events": {
          to: "note_events";
          many: true;
        };
      };
      hasPrimaryKey: true;
    };
    // ... boards, note_events
  }
}`;

const REGISTRATION = `// server/index.ts, inside createApp({ plugins: [...] })
database({
  schema,
  // All tables are readable; only boards and notes accept HTTP writes.
  api: { writes: { tables: ["boards", "notes"] } },
  hooks: { /* inline hooks shown below */ },
})`;

const PRIVATE_COLUMN = `const notes = table("notes", {
  // ...
  author: text().notNull(),
  author_email: text().private(),
});

// Server-side, it is an ordinary column.
const note = await db.notes.find(id);       // note.author_email — typed
await db.notes.create({ author_email });     // accepted

// Over HTTP, the same declaration removes it from every surface:
// the select list, where, the create body, and the update body.`;

const INLINE_HOOKS = `// server/index.ts
// Model-based redaction is best-effort, not a privacy guarantee.
const redactor = createAgent({
  instructions:
    "Replace every personal name and email address in the user's text with [redacted]. " +
    "Return only the rewritten text, nothing else.",
});

database({
  schema,
  api: { writes: { tables: ["boards", "notes"] } },
  hooks: {
    notes: {
      async beforeCreate(values) {
        // Cancel the model request before the 30-second transaction deadline.
        const signal = AbortSignal.timeout(10_000);
        const answer = await runAgent(redactor, {
          messages: String(values.body),
          signal,
        });
        // A cancelled stream can return partial text instead of throwing.
        signal.throwIfAborted();
        if (answer.events.some(event =>
          event.type === "status" && event.status === "error"
        )) {
          throw new Error("Note redaction failed");
        }
        const body = answer.text.trim();
        if (!body) throw new Error("Note redaction returned no text");

        return {
          ...values,
          body,
          // Demo only; production apps should use the authenticated session.
          author_email: \`\${values.author}@example.com\`,
        };
      },

      async afterCreate(row, ctx) {
        // HTTP writes are disabled for this table, but this client is trusted
        // and bound to the note's transaction.
        await ctx.app.database.note_events.create({
          note_id: row.id,
          action: "created",
        });
      },

      serialize: (row, { operation }) =>
        operation === "list"
          ? { ...row, body: String(row.body).slice(0, 120) }
          : row,
    },
  },
});`;

const TIMELINE_QUERY = `// Browser: use the generated board detail route, not a custom controller.
const include = encodeURIComponent(JSON.stringify({
  notes: {
    limit: 20,
    include: { note_events: { limit: 5 } },
  },
}));
const response = await fetch(
  \`/api/database/boards/\${boardId}?include=\${include}\`,
);
if (!response.ok) throw new Error("Failed to load board timeline");
const board = await response.json();`;

/** The five default CRUD routes for each exposed table with a public primary key. */
const GENERATED_ROUTES = [
  {
    method: "GET",
    suffix: "",
    purpose: "List with filters, order, pagination and includes",
  },
  { method: "GET", suffix: "/:id", purpose: "One row by primary key" },
  {
    method: "POST",
    suffix: "",
    purpose: "Create, with before/after hooks in one transaction",
  },
  {
    method: "PATCH",
    suffix: "/:id",
    purpose: "Partial update against the generated update schema",
  },
  {
    method: "DELETE",
    suffix: "/:id",
    purpose: "Delete one row, with the same hooks available",
  },
] as const;

const METHOD_TONE: Record<string, string> = {
  GET: "text-emerald-600 dark:text-emerald-400",
  POST: "text-blue-600 dark:text-blue-400",
  PATCH: "text-amber-600 dark:text-amber-400",
  DELETE: "text-red-600 dark:text-red-400",
};

function RouteTable() {
  return (
    <div className="space-y-6">
      {["boards", "notes", "note_events"].map((table) => (
        <div key={table}>
          <div className="flex items-center gap-2 mb-2">
            <code className="text-sm font-semibold">{table}</code>
            <Badge variant={table === "note_events" ? "outline" : "secondary"}>
              {table === "note_events" ? "read-only" : "full CRUD"}
            </Badge>
          </div>
          <div className="rounded-md border divide-y">
            {GENERATED_ROUTES.filter(
              (route) => table !== "note_events" || route.method === "GET",
            ).map((route) => (
              <div
                key={`${route.method}${route.suffix}`}
                className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-4 px-3 py-2"
              >
                <code
                  className={`text-xs font-bold w-16 shrink-0 ${METHOD_TONE[route.method]}`}
                >
                  {route.method}
                </code>
                <code className="text-xs sm:w-72 shrink-0">
                  /api/database/{table}
                  {route.suffix}
                </code>
                <span className="text-xs text-muted-foreground">
                  {route.purpose}
                </span>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

function DatabaseRoute() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-6xl mx-auto px-6 py-12">
        <Header
          title="Database"
          description="Declare a Postgres schema once and get typed entities, generated CRUD routes, and transactional hooks — without writing a controller."
          tooltip="The DatabasePlugin reads an explicit schema. It never creates, migrates, or introspects tables."
        />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Live</CardTitle>
              <CardDescription>
                Boards, their notes, and the audit trail a hook keeps for them.
                Every request below hits a route this app never wrote.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <BoardExplorer />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>1. Declare the schema</CardTitle>
              <CardDescription>
                Columns and foreign keys in TypeScript. The plugin expects these
                tables to already exist — it owns no migrations.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CodeBlock code={SCHEMA_EXAMPLE} />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>2. Types follow</CardTitle>
              <CardDescription>
                <code className="text-xs">appkit generate-types</code> turns the
                schema into a registry augmentation, so rows, filters, and
                includes are checked at compile time.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CodeBlock code={GENERATED_TYPES} />
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>3. Restrict the generated API</CardTitle>
              <CardDescription>
                Declared tables get full CRUD routes by default. Use api to
                restrict the exposed tables and write operations.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="rounded-md border-l-4 border-l-primary bg-muted/40 px-4 py-3">
                <p className="text-sm font-medium">
                  Full CRUD is enabled by default.
                </p>
                <p className="text-sm text-muted-foreground mt-1">
                  Set <code>api: false</code> to disable generated endpoints
                  while keeping the typed database client available to your own
                  routes and hooks. Use <code>api: {"{ writes: false }"}</code>{" "}
                  for read-only routes on every table. Here,{" "}
                  <code>api.writes.tables</code> allows writes to boards and
                  notes while keeping the audit trail read-only.
                </p>
              </div>
              <CodeBlock code={REGISTRATION} />
              <RouteTable />
              <div className="space-y-2">
                <p className="text-sm font-medium">
                  Try writing directly to the read-only audit trail
                </p>
                <RefusalProbe
                  label="Create an audit event over HTTP: no write route is registered"
                  request="POST /api/database/note_events"
                  send={() =>
                    fetch("/api/database/note_events", {
                      method: "POST",
                      headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({ note_id: 1, action: "created" }),
                    })
                  }
                />
              </div>
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Private columns</CardTitle>
              <CardDescription>
                <code className="text-xs">private()</code> marks a column the
                server owns. It is the same declaration that keeps it out of
                four separate request surfaces.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <CodeBlock code={PRIVATE_COLUMN} />
              <p className="text-sm text-muted-foreground">
                A private column is dropped from the select list before the
                query is built, so it never leaves Postgres; it is refused in{" "}
                <code>where</code>, so nobody can guess it a character at a
                time; it is refused in write bodies rather than quietly ignored;
                and it is stripped on the way out even if a serializer puts it
                back. Server code, meanwhile, reads and writes it normally —
                which is how <code>author_email</code> gets set at all.
              </p>
              <div className="space-y-2">
                <RefusalProbe
                  label="Read it"
                  request="GET /api/database/notes — author_email is simply absent"
                  send={() => fetch("/api/database/notes?limit=1")}
                />
                <RefusalProbe
                  label="Filter by it"
                  request={`GET /api/database/notes?where={"author_email":"victor@example.com"}`}
                  send={() =>
                    fetch(
                      `/api/database/notes?where=${encodeURIComponent(
                        JSON.stringify({ author_email: "victor@example.com" }),
                      )}`,
                    )
                  }
                />
                <RefusalProbe
                  label="Write it"
                  request={`POST /api/database/notes with "author_email"`}
                  send={() =>
                    fetch("/api/database/notes", {
                      method: "POST",
                      headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({
                        board_id: 1,
                        author: "intruder",
                        body: "trying to set a private column",
                        author_email: "intruder@example.com",
                      }),
                    })
                  }
                />
              </div>
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>The lifecycle of one write</CardTitle>
              <CardDescription>
                Where your code runs, and what it is allowed to do there. This
                is the flow the panel at the top of the page executes.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <HookLifecycle />
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Inline hooks</CardTitle>
              <CardDescription>
                Redaction, audit writes, and read previews are defined directly
                in the plugin registration, without a wrapper or custom routes.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <CodeBlock code={INLINE_HOOKS} />
              <p className="text-sm text-muted-foreground">
                A hook needs nothing from the plugin system to do this.{" "}
                <code>createAgent</code> returns a definition, and the inline
                hook passes it to <code>runAgent</code>. The capability from{" "}
                <code>ctx</code> is <code>ctx.app.database</code>, which is
                bound to the current transaction. Calls to a model or another
                service do not join that transaction, and rollback cannot undo
                their external effects.
              </p>
              <p className="text-sm text-muted-foreground">
                The model request receives a 10-second cancellation signal,
                shorter than the database transaction's 30-second deadline.
                Cancellation, an agent error status, or blank output rejects the
                mutation instead of saving the original or partial text. The
                transaction occupies a pooled connection while it waits, so keep
                this work short.
              </p>
              <p className="text-sm text-muted-foreground">
                This demonstrates best-effort redaction, not guaranteed removal
                of personal data. A non-empty model response can still miss
                names or email addresses; do not use it as the sole privacy
                control for sensitive data.
              </p>
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardHeader>
              <CardTitle>Nested reads through the generated API</CardTitle>
              <CardDescription>
                Load a board, its notes, and their audit events in one bounded
                read. A read-only table can participate in includes without
                exposing write operations.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <CodeBlock code={TIMELINE_QUERY} />
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
