// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx appkit-generate-types' or Vite plugin during build
import "@databricks/app-kit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/app-kit-ui/js";

declare module "@databricks/app-kit-ui/react" {
  interface QueryRegistry {
    apps_list: {
        name: "apps_list";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          creator: string;
          /** @sqlType STRING */
          tags: string;
          /** @sqlType DECIMAL(38,6) */
          totalSpend: number;
          /** @sqlType DATE */
          createdAt: string;
        }>;
      };
    cost_recommendations: {
        name: "cost_recommendations";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType INT */
          dummy: number;
        }>;
      };
    example: {
        name: "example";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BOOLEAN */
          "(1 = 1)": boolean;
        }>;
      };
    spend_data: {
        name: "spend_data";
        parameters: {
          /** STRING - use sql.string() */
          groupBy: SQLStringMarker;
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
          /** STRING - use sql.string() */
          appId: SQLStringMarker;
          /** STRING - use sql.string() */
          creator: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          group_key: string;
          /** @sqlType TIMESTAMP */
          aggregation_period: string;
          /** @sqlType DECIMAL(38,6) */
          cost_usd: number;
        }>;
      };
    spend_summary: {
        name: "spend_summary";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType DECIMAL(33,0) */
          total: number;
          /** @sqlType DECIMAL(33,0) */
          average: number;
          /** @sqlType DECIMAL(33,0) */
          forecasted: number;
        }>;
      };
    sql_helpers_test: {
        name: "sql_helpers_test";
        parameters: {
          /** STRING - use sql.string() */
          stringParam: SQLStringMarker;
          /** NUMERIC - use sql.number() */
          numberParam: SQLNumberMarker;
          /** BOOLEAN - use sql.boolean() */
          booleanParam: SQLBooleanMarker;
          /** DATE - use sql.date() */
          dateParam: SQLDateMarker;
          /** TIMESTAMP - use sql.timestamp() */
          timestampParam: SQLTimestampMarker;
          /** STRING - use sql.string() */
          binaryParam: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          string_value: string;
          /** @sqlType STRING */
          number_value: string;
          /** @sqlType STRING */
          boolean_value: string;
          /** @sqlType STRING */
          date_value: string;
          /** @sqlType STRING */
          timestamp_value: string;
          /** @sqlType BINARY */
          binary_value: string;
          /** @sqlType STRING */
          binary_hex: string;
          /** @sqlType INT */
          binary_length: number;
        }>;
      };
    top_contributors: {
        name: "top_contributors";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType DECIMAL(38,6) */
          total_cost_usd: number;
        }>;
      };
    untagged_apps: {
        name: "untagged_apps";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType STRING */
          creator: string;
          /** @sqlType DECIMAL(38,6) */
          total_cost_usd: number;
          /** @sqlType DECIMAL(38,10) */
          avg_period_cost_usd: number;
        }>;
      };
  }
}
