// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    app_activity_heatmap: {
        name: "app_activity_heatmap";
        parameters: {
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          ;
        }>;
      };
    apps_list: {
        name: "apps_list";
        parameters: Record<string, never>;
        result: Array<{
          ;
        }>;
      };
    cost_recommendations: {
        name: "cost_recommendations";
        parameters: Record<string, never>;
        result: Array<{
          ;
        }>;
      };
    example: {
        name: "example";
        parameters: Record<string, never>;
        result: Array<{
          ;
        }>;
      };
    spend_data: {
        name: "spend_data";
        parameters: {
          /** STRING - use sql.string() */
          groupBy: SQLStringMarker;
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
          /** STRING - use sql.string() */
          appId: SQLStringMarker;
          /** STRING - use sql.string() */
          creator: SQLStringMarker;
        };
        result: Array<{
          ;
        }>;
      };
    spend_summary: {
        name: "spend_summary";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
        };
        result: Array<{
          ;
        }>;
      };
    sql_helpers_test: {
        name: "sql_helpers_test";
        parameters: {
          /** STRING - use sql.string() */
          stringParam: SQLStringMarker;
          /** NUMERIC - use sql.number() */
          numberParam: SQLNumberMarker;
          /** BOOLEAN - use sql.boolean() */
          booleanParam: SQLBooleanMarker;
          /** DATE - use sql.date() */
          dateParam: SQLDateMarker;
          /** TIMESTAMP - use sql.timestamp() */
          timestampParam: SQLTimestampMarker;
          /** STRING - use sql.string() */
          binaryParam: SQLStringMarker;
        };
        result: Array<{
          ;
        }>;
      };
    top_contributors: {
        name: "top_contributors";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          ;
        }>;
      };
    untagged_apps: {
        name: "untagged_apps";
        parameters: {
          /** STRING - use sql.string() */
          aggregationLevel: SQLStringMarker;
          /** DATE - use sql.date() */
          startDate: SQLDateMarker;
          /** DATE - use sql.date() */
          endDate: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          app_name: string;
          /** @sqlType STRING */
          creator: string;
          /** @sqlType DECIMAL(38,6) */
          total_cost_usd: number;
          /** @sqlType DECIMAL(38,10) */
          avg_period_cost_usd: number;
        }>;
      };
  }
}
