import {
  type MetricsMetadataBundle,
  registerMetricsMetadata,
} from "@databricks/appkit-ui/format";
import { createRouter, RouterProvider } from "@tanstack/react-router";
import React from "react";
import ReactDOM from "react-dom/client";
// Build-time-emitted metadata bundle. In a production app this file is
// regenerated by `npx @databricks/appkit metric sync` (or the Vite plugin)
// from `config/queries/metric.json`. Phase 7 ships a hand-authored copy so
// the demo route at `/metrics` can wire format specs into Plotly even when
// the dev workspace does not host the underlying UC metric views.
import metricsMetadata from "../../shared/appkit-types/metrics.metadata.json";
import { routeTree } from "./routeTree.gen";
import "./index.css";

// Register the metric metadata bundle once at startup so `useMetricView()`'s
// `metadata` field is populated for every consumer in the app. The cast is
// load-bearing: TypeScript widens JSON-imported string literals (`"sp"`) to
// `string`, which the bundle's `lane: "sp" | "obo"` discriminant rejects.
// The actual JSON values are hand-checked against the schema.
registerMetricsMetadata(metricsMetadata as unknown as MetricsMetadataBundle);

const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  defaultStaleTime: 5000,
  scrollRestoration: true,
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById("root");
if (!rootElement) {
  throw new Error("Root element not found");
}

ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
);
