/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ReconnectRouteRouteImport } from "./routes/reconnect.route";
import { Route as AnalyticsRouteRouteImport } from "./routes/analytics.route";
import { Route as IndexRouteImport } from "./routes/index";

const ReconnectRouteRoute = ReconnectRouteRouteImport.update({
  id: "/reconnect",
  path: "/reconnect",
  getParentRoute: () => rootRouteImport,
} as any);
const AnalyticsRouteRoute = AnalyticsRouteRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRouteRoute;
  "/reconnect": typeof ReconnectRouteRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRouteRoute;
  "/reconnect": typeof ReconnectRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/analytics": typeof AnalyticsRouteRoute;
  "/reconnect": typeof ReconnectRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/analytics" | "/reconnect";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/analytics" | "/reconnect";
  id: "__root__" | "/" | "/analytics" | "/reconnect";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AnalyticsRouteRoute: typeof AnalyticsRouteRoute;
  ReconnectRouteRoute: typeof ReconnectRouteRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/reconnect": {
      id: "/reconnect";
      path: "/reconnect";
      fullPath: "/reconnect";
      preLoaderRoute: typeof ReconnectRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/analytics": {
      id: "/analytics";
      path: "/analytics";
      fullPath: "/analytics";
      preLoaderRoute: typeof AnalyticsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRouteRoute: AnalyticsRouteRoute,
  ReconnectRouteRoute: ReconnectRouteRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
