import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";

const __dirname = dirname(fileURLToPath(import.meta.url));

async function buildStyles(): Promise<void> {
  try {
    const sourceCSS = resolve(
      __dirname,
      "../../packages/appkit-ui/src/react/styles/globals.css",
    );
    const outputDir = resolve(__dirname, "../static/appkit-ui");
    const outputCSS = resolve(outputDir, "styles.gen.css");

    let css = await readFile(sourceCSS, "utf-8");

    // Rewrite @source path for docs build
    // The original @source "./react" is correct for the package, but during docs build
    // we need @source "../" because the CSS file path context is different during PostCSS
    // processing. This allows Tailwind to find and scan the React component files in
    // packages/appkit-ui/src/react to generate all the utility classes they use.
    css = css.replace('@source "./react"', '@source "../"');

    const result = await postcss([tailwindcss()]).process(css, {
      from: sourceCSS,
      to: outputCSS,
    });

    await mkdir(outputDir, { recursive: true });

    // Add comment after PostCSS processing so it doesn't get stripped out
    const finalCSS = `/* Auto-generated by docs/scripts/build-appkit-ui-styles.ts */\n${result.css}`;

    await writeFile(outputCSS, finalCSS, "utf-8");

    console.log(
      "[build-appkit-ui-styles] ✓ appkit-ui CSS build complete! Output size:",
      (result.css.length / 1024).toFixed(2),
      "KB",
    );
  } catch (error) {
    console.error("[build-styles] ✗ Error building styles:", error);
    process.exit(1);
  }
}

buildStyles();
