// Auto-generated by AppKit - DO NOT EDIT
import "@databricks/appkit";
import "@databricks/appkit-ui/js/beta";

type DatabaseLogicalFilter<T> = T & {
  and?: readonly DatabaseLogicalFilter<T>[];
  or?: readonly DatabaseLogicalFilter<T>[];
};

interface GeneratedDatabaseRegistry {
  "boards": {
    row: {
      "id": number;
      "slug": string;
      "title": string;
      "created_at": string;
    };
    publicRow: {
      "id": number;
      "slug": string;
      "title": string;
      "created_at": string;
    };
    insert: {
      "slug": string;
      "title": string;
      "created_at"?: string;
    };
    update: {
      "slug"?: string;
      "title"?: string;
      "created_at"?: string;
    };
    filters: DatabaseLogicalFilter<{
      "id"?: number | readonly (number)[] | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
      "slug"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
      "title"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
      "created_at"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; gt?: string; gte?: string; lt?: string; lte?: string; };
    }>;
    includes: {
      "notes": { to: "notes"; many: true };
    };
    hasPrimaryKey: true;
    api: {
      insert: {
        "slug": string;
        "title": string;
        "created_at"?: string;
      };
      update: {
        "slug"?: string;
        "title"?: string;
      };
      filters: DatabaseLogicalFilter<{
        "id"?: number | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
        "slug"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
        "title"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
        "created_at"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; gt?: string; gte?: string; lt?: string; lte?: string; };
      }>;
      orderable: "id" | "slug" | "title" | "created_at";
      key: "id";
    };
  };
  "notes": {
    row: {
      "id": number;
      "board_id": number;
      "author": string;
      "author_email": string | null;
      "body": string;
      "created_at": string;
    };
    publicRow: {
      "id": number;
      "board_id": number;
      "author": string;
      "body": string;
      "created_at": string;
    };
    insert: {
      "board_id": number;
      "author": string;
      "author_email"?: string | null;
      "body": string;
      "created_at"?: string;
    };
    update: {
      "board_id"?: number;
      "author"?: string;
      "author_email"?: string | null;
      "body"?: string;
      "created_at"?: string;
    };
    filters: DatabaseLogicalFilter<{
      "id"?: number | readonly (number)[] | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
      "board_id"?: number | readonly (number)[] | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
      "author"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
      "author_email"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; is?: null; };
      "body"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
      "created_at"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; gt?: string; gte?: string; lt?: string; lte?: string; };
    }>;
    includes: {
      "boards": { to: "boards"; many: false };
      "note_events": { to: "note_events"; many: true };
    };
    hasPrimaryKey: true;
    api: {
      insert: {
        "board_id": number;
        "author": string;
        "body": string;
        "created_at"?: string;
      };
      update: {
        "board_id"?: number;
        "author"?: string;
        "body"?: string;
      };
      filters: DatabaseLogicalFilter<{
        "id"?: number | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
        "board_id"?: number | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
        "author"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
        "body"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
        "created_at"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; gt?: string; gte?: string; lt?: string; lte?: string; };
      }>;
      orderable: "id" | "board_id" | "author" | "body" | "created_at";
      key: "id";
    };
  };
  "note_events": {
    row: {
      "id": number;
      "note_id": number;
      "action": string;
      "created_at": string;
    };
    publicRow: {
      "id": number;
      "note_id": number;
      "action": string;
      "created_at": string;
    };
    insert: {
      "note_id": number;
      "action": string;
      "created_at"?: string;
    };
    update: {
      "note_id"?: number;
      "action"?: string;
      "created_at"?: string;
    };
    filters: DatabaseLogicalFilter<{
      "id"?: number | readonly (number)[] | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
      "note_id"?: number | readonly (number)[] | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
      "action"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
      "created_at"?: string | readonly (string)[] | { eq?: string; neq?: string; in?: readonly (string)[]; gt?: string; gte?: string; lt?: string; lte?: string; };
    }>;
    includes: {
      "notes": { to: "notes"; many: false };
    };
    hasPrimaryKey: true;
    api: {
      insert: {
        "note_id": number;
        "action": string;
        "created_at"?: string;
      };
      update: {
        "note_id"?: number;
        "action"?: string;
      };
      filters: DatabaseLogicalFilter<{
        "id"?: number | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
        "note_id"?: number | { eq?: number; neq?: number; in?: readonly (number)[]; gt?: number; gte?: number; lt?: number; lte?: number; };
        "action"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; like?: string; ilike?: string; };
        "created_at"?: string | { eq?: string; neq?: string; in?: readonly (string)[]; gt?: string; gte?: string; lt?: string; lte?: string; };
      }>;
      orderable: "id" | "note_id" | "action" | "created_at";
      key: "id";
    };
  };
}

declare module "@databricks/appkit" {
  interface DatabaseRegistry extends GeneratedDatabaseRegistry {}
}

declare module "@databricks/appkit-ui/js/beta" {
  interface DatabaseRegistry extends GeneratedDatabaseRegistry {}
}
