// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
declare module "@databricks/appkit-ui/react" {
  interface MetricRegistry {
    "revenue": {
      key: "revenue";
      source: "appkit_demo.public.revenue_metrics";
      lane: "sp";
      measures: Record<string, never>;
      dimensions: Record<string, never>;
      measureKeys: never;
      dimensionKeys: never;
      timeGrains: never;
      metadata: {
        measures: Record<string, never>;
        dimensions: Record<string, never>;
      };
    };
    "customer_metrics": {
      key: "customer_metrics";
      source: "appkit_demo.public.customer_metrics";
      lane: "obo";
      measures: {
      /** @sqlType bigint */
      "active_accounts": number;
      /** @sqlType decimal */
      "churn_rate": number;
      /** @sqlType double */
      "avg_ltv": number;
    };
      dimensions: {
      /** @sqlType string */
      "segment": string;
      /** @sqlType string */
      "region": string;
      /** @sqlType string */
      "csm_email": string;
    };
      measureKeys: "active_accounts" | "churn_rate" | "avg_ltv";
      dimensionKeys: "segment" | "region" | "csm_email";
      timeGrains: never;
      metadata: {
        measures: {
      "active_accounts": {
        type: "bigint";
        display_name: "Active Accounts";
      };
      "churn_rate": {
        type: "decimal";
        display_name: "Churn Rate";
      };
      "avg_ltv": {
        type: "double";
        display_name: "Average LTV";
      };
    };
        dimensions: {
      "segment": {
        type: "string";
        display_name: "Customer Segment";
      };
      "region": {
        type: "string";
        display_name: "Region";
      };
      "csm_email": {
        type: "string";
        display_name: "CSM Email";
      };
    };
      };
    };
  }
}
