// Auto-generated by AppKit - DO NOT EDIT
// In a production app this file is regenerated by `npx @databricks/appkit metric sync`
// or the Vite type-generator plugin. Phase 7 ships this hand-authored copy so the
// dev-playground demo at /metrics compiles even when the dev workspace does not
// host the underlying UC metric views — the typed surface is what we want to
// showcase.
import "@databricks/appkit-ui/react";

declare module "@databricks/appkit-ui/react" {
  interface MetricRegistry {
    revenue: {
      key: "revenue";
      source: "appkit_demo.public.revenue_metrics";
      lane: "sp";
      measures: {
        /** @sqlType DECIMAL(38,2) */
        arr: number;
        /** @sqlType DECIMAL(38,2) */
        mrr: number;
        /** @sqlType DECIMAL(38,2) */
        new_arr: number;
        /** @sqlType DECIMAL(38,2) */
        churned_arr: number;
      };
      dimensions: {
        /** @sqlType STRING */
        region: string;
        /** @sqlType STRING */
        segment: string;
        /** @sqlType TIMESTAMP @timeGrain day|week|month|quarter|year */
        created_at: string;
      };
      measureKeys: "arr" | "mrr" | "new_arr" | "churned_arr";
      dimensionKeys: "region" | "segment" | "created_at";
      timeGrains: "day" | "week" | "month" | "quarter" | "year";
      metadata: {
        measures: {
          arr: {
            type: "DECIMAL(38,2)";
            display_name: "Annual Recurring Revenue";
            format: "$#,##0.00";
            description: "Annualized contract value across all active subscriptions";
          };
          mrr: {
            type: "DECIMAL(38,2)";
            display_name: "Monthly Recurring Revenue";
            format: "$#,##0.00";
          };
          new_arr: {
            type: "DECIMAL(38,2)";
            display_name: "New ARR";
            format: "$#,##0.00";
          };
          churned_arr: {
            type: "DECIMAL(38,2)";
            display_name: "Churned ARR";
            format: "$#,##0.00";
          };
        };
        dimensions: {
          region: {
            type: "STRING";
            display_name: "Region";
          };
          segment: {
            type: "STRING";
            display_name: "Customer Segment";
          };
          created_at: {
            type: "TIMESTAMP";
            display_name: "Subscription Start";
            time_grain: readonly ["day", "week", "month", "quarter", "year"];
          };
        };
      };
    };
    customer_metrics: {
      key: "customer_metrics";
      source: "appkit_demo.public.customer_metrics";
      lane: "obo";
      measures: {
        /** @sqlType BIGINT */
        active_accounts: number;
        /** @sqlType DECIMAL(10,4) */
        churn_rate: number;
        /** @sqlType DECIMAL(38,2) */
        avg_ltv: number;
      };
      dimensions: {
        /** @sqlType STRING */
        segment: string;
        /** @sqlType STRING */
        region: string;
        /** @sqlType STRING */
        csm_email: string;
      };
      measureKeys: "active_accounts" | "churn_rate" | "avg_ltv";
      dimensionKeys: "segment" | "region" | "csm_email";
      timeGrains: never;
      metadata: {
        measures: {
          active_accounts: {
            type: "BIGINT";
            display_name: "Active Accounts";
            format: "#,##0";
          };
          churn_rate: {
            type: "DECIMAL(10,4)";
            display_name: "Churn Rate";
            format: "0.0%";
          };
          avg_ltv: {
            type: "DECIMAL(38,2)";
            display_name: "Average LTV";
            format: "$#,##0.00";
          };
        };
        dimensions: {
          segment: {
            type: "STRING";
            display_name: "Customer Segment";
          };
          region: {
            type: "STRING";
            display_name: "Region";
          };
          csm_email: {
            type: "STRING";
            display_name: "CSM Email";
          };
        };
      };
    };
  }
}
