// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import type {} from "@databricks/appkit-ui/react";
declare module "@databricks/appkit-ui/react" {
  interface MetricRegistry {
    "customers": {
      key: "customers";
      source: "appkit_demo.public.customer_metrics";
      lane: "obo";
      measures: {
      /** @sqlType bigint */
      "active_accounts": string | null;
      /** @sqlType decimal */
      "churn_rate": string | null;
      /** @sqlType double */
      "avg_ltv": string | null;
    };
      dimensions: {
      /** @sqlType string */
      "segment": string | null;
      /** @sqlType string */
      "region": string | null;
      /** @sqlType string */
      "csm_email": string | null;
    };
      measureKeys: "active_accounts" | "churn_rate" | "avg_ltv";
      dimensionKeys: "segment" | "region" | "csm_email";
      timeGrains: never;
      metadata: {
        measures: {
      "active_accounts": {
        type: "bigint";
        display_name: "Active Accounts";
        format: "#,##0";
      };
      "churn_rate": {
        type: "decimal";
        display_name: "Churn Rate";
      };
      "avg_ltv": {
        type: "double";
        display_name: "Average LTV";
        format: "$#,##0.00";
      };
    };
        dimensions: {
      "segment": {
        type: "string";
        display_name: "Customer Segment";
      };
      "region": {
        type: "string";
        display_name: "Region";
      };
      "csm_email": {
        type: "string";
        display_name: "CSM Email";
      };
    };
      };
    };
    "revenue": {
      key: "revenue";
      source: "appkit_demo.public.revenue_metrics";
      lane: "sp";
      measures: {
      /** @sqlType double */
      "mrr": string | null;
      /** @sqlType double */
      "arr": string | null;
      /** @sqlType double */
      "new_arr": string | null;
      /** @sqlType double */
      "churned_arr": string | null;
    };
      dimensions: {
      /** @sqlType string */
      "region": string | null;
      /** @sqlType string */
      "segment": string | null;
      /** @sqlType timestamp_ltz @timeGrain day|hour|minute|month|quarter|week|year */
      "created_at": string | null;
    };
      measureKeys: "mrr" | "arr" | "new_arr" | "churned_arr";
      dimensionKeys: "region" | "segment" | "created_at";
      timeGrains: "day" | "hour" | "minute" | "month" | "quarter" | "week" | "year";
      metadata: {
        measures: {
      "mrr": {
        type: "double";
        display_name: "Monthly Recurring Revenue";
        format: "$#,##0.00";
      };
      "arr": {
        type: "double";
        display_name: "Annual Recurring Revenue";
        format: "$#,##0.00";
        description: "Annualized contract value across all active subscriptions";
      };
      "new_arr": {
        type: "double";
        display_name: "New ARR";
        format: "$#,##0.00";
      };
      "churned_arr": {
        type: "double";
        display_name: "Churned ARR";
        format: "$#,##0.00";
      };
    };
        dimensions: {
      "region": {
        type: "string";
        display_name: "Region";
      };
      "segment": {
        type: "string";
        display_name: "Customer Segment";
      };
      "created_at": {
        type: "timestamp_ltz";
        display_name: "Subscription Start";
        time_grain: readonly ["day", "hour", "minute", "month", "quarter", "week", "year"];
      };
    };
      };
    };
  }
}
