import { randomUUID } from "node:crypto";
import fsSync from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";

import type { Schema } from "../../database/schema-builder";
import { assertFinalizedSchema } from "../../database/schema-builder/define-schema";
import { walkSchema } from "./walk-schema";

/** Safe diagnostic raised when database declarations cannot be generated. */
export class DatabaseTypegenError extends Error {
  constructor(message = "Database schema generation failed") {
    super(message);
    this.name = "DatabaseTypegenError";
  }
}

interface GenerateDatabaseTypesOptions {
  readonly schemaFile: string;
  readonly outFile: string;
}

export const DATABASE_TYPES_FILE = "database.d.ts";

function schemaLabel(schemaFile: string): string {
  return path.relative(process.cwd(), schemaFile) || schemaFile;
}

function importFailureReason(error: unknown): string {
  if (error instanceof SyntaxError) return "could not be parsed";
  let code: unknown;
  try {
    code =
      error && typeof error === "object"
        ? Reflect.get(error, "code")
        : undefined;
  } catch {
    code = undefined;
  }
  if (code === "MODULE_NOT_FOUND" || code === "ERR_MODULE_NOT_FOUND") {
    return "contains an unresolved import";
  }
  return "threw while loading";
}

/** Empty augmentation used when no valid database schema is available. */
export const NEUTRAL_DATABASE_TYPES = `// Auto-generated by AppKit - DO NOT EDIT
import "@databricks/appkit";

declare module "@databricks/appkit" {
  interface DatabaseRegistry {}
}
`;

/** Render one `DatabaseRegistry` augmentation from a finalized schema. */
function render(schema: Schema): string {
  const entries = walkSchema(schema)
    .map(
      (entry) => `    ${JSON.stringify(entry.name)}: {
      row: ${entry.row};
      publicRow: ${entry.publicRow};
      insert: ${entry.insert};
      update: ${entry.update};
      filters: ${entry.filters};
      includes: ${entry.includes};
      hasPrimaryKey: ${entry.hasPrimaryKey};
    };`,
    )
    .join("\n");
  return `// Auto-generated by AppKit - DO NOT EDIT
import "@databricks/appkit";

declare module "@databricks/appkit" {
  type DatabaseLogicalFilter<T> = T & {
    and?: readonly DatabaseLogicalFilter<T>[];
    or?: readonly DatabaseLogicalFilter<T>[];
  };

  interface DatabaseRegistry {
${entries}
  }
}
`;
}

/** Atomically replace generated output only when its content changes. */
async function writeIfChanged(outFile: string, content: string): Promise<void> {
  if (
    fsSync.existsSync(outFile) &&
    (await fs.readFile(outFile, "utf8")) === content
  )
    return;
  await fs.mkdir(path.dirname(outFile), { recursive: true });
  const temporary = path.join(
    path.dirname(outFile),
    `.${path.basename(outFile)}.${randomUUID()}.tmp`,
  );
  try {
    await fs.writeFile(temporary, content, "utf8");
    await fs.rename(temporary, outFile);
  } finally {
    await fs.rm(temporary, { force: true });
  }
}

/** Disable Jiti's module cache so watch-mode runs observe schema edits. */
async function importSchema(schemaFile: string): Promise<unknown> {
  const { createJiti } = await import("jiti");
  return createJiti(import.meta.url, { moduleCache: false }).import(schemaFile);
}

/** Generate current registry types or neutralize them when loading fails. */
export async function generateDatabaseTypes(
  options: GenerateDatabaseTypesOptions,
): Promise<void> {
  if (!fsSync.existsSync(options.schemaFile)) {
    await writeIfChanged(options.outFile, NEUTRAL_DATABASE_TYPES);
    return;
  }
  try {
    const module = (await importSchema(options.schemaFile)) as {
      schema?: Schema;
    };
    if (!("schema" in module)) {
      throw new DatabaseTypegenError(
        `Database schema module "${schemaLabel(options.schemaFile)}" must export a named "schema"`,
      );
    }
    try {
      assertFinalizedSchema(module.schema);
    } catch {
      throw new DatabaseTypegenError(
        `Database schema "${schemaLabel(options.schemaFile)}" is not a finalized AppKit schema`,
      );
    }
    await writeIfChanged(options.outFile, render(module.schema));
  } catch (error) {
    // A failed run must not leave stale entities visible to TypeScript.
    await writeIfChanged(options.outFile, NEUTRAL_DATABASE_TYPES);
    throw error instanceof DatabaseTypegenError
      ? error
      : new DatabaseTypegenError(
          `Database schema "${schemaLabel(options.schemaFile)}" ${importFailureReason(error)}`,
        );
  }
}
