// Auto-generated by AppKit - DO NOT EDIT
// Generated at: 2025-11-27T16:48:55.599Z

import "@databricks/app-kit-ui/react";

declare module "@databricks/app-kit-ui/react" {
  interface PluginRegistry {
    reconnect: {
      "/": {
          message: string;
      };
      "/stream": {
          type: string;
          count: number;
          total: number;
          timestamp: string;
          content: string;
      };
    }
    analytics: {
      "/users/me/query/:query_key": {
          chunk_index: number;
          row_offset: number;
          row_count: number;
          data: any[];
      };
      "/query/:query_key": {
          chunk_index: number;
          row_offset: number;
          row_count: number;
          data: any[];
      };
    }
  }

  interface QueryRegistry {
    apps_list: {
        id: string;
        name: string;
        creator: string;
        tags: string[];
        totalSpend: number;
        createdAt: string;
    }[];
    spend_summary: {
        total: number;
        average: number;
        forecasted: number;
    }[];
    untagged_apps: {
        app_name: string;
        creator: string;
        total_cost_usd: number;
        avg_period_cost_usd: number;
    }[];
    spend_data: {
        group_key: string;
        aggregation_period: string;
        cost_usd: number;
    }[];
    top_contributors: {
        app_name: string;
        total_cost_usd: number;
    }[];
  }

}
