import fs from "node:fs";
import path from "node:path";
import { routeSchemaRegistry } from "../plugin";
import type { QuerySchemas } from "shared";
import { createAuxiliaryTypeStore, printNode, zodToTs } from "zod-to-ts";

interface PluginTypeInfo {
  name: string;
}

function indentType(typeString: string, baseIndent: string): string {
  const lines = typeString.split("\n");
  if (lines.length === 1) return typeString;

  return lines
    .map((line, index) => (index === 0 ? line : baseIndent + line))
    .join("\n");
}

export function generatePluginTypes(
  plugins: PluginTypeInfo[],
  querySchemas: QuerySchemas,
): void {
  const auxiliaryTypeStore = createAuxiliaryTypeStore();

  const pluginTypes = plugins
    .map((p) => {
      const routes = routeSchemaRegistry.get(p.name);
      if (!routes || routes.size === 0) return null;

      const routeTypes = Array.from(routes.entries())
        .map(([route, schema]) => {
          const { node } = zodToTs(schema, { auxiliaryTypeStore });
          const typeString = printNode(node);
          return `      "${route}": ${indentType(typeString, "      ")};`;
        })
        .join("\n");
      return `    ${p.name}: {\n${routeTypes}\n    }`;
    })
    .filter(Boolean)
    .join("\n");

  const auxiliaryTypes = Array.from(auxiliaryTypeStore.definitions.values())
    .map((definition) => printNode(definition.node))
    .join("\n");

  const auxiliaryPreamble = auxiliaryTypes ? `${auxiliaryTypes}\n\n` : "";
  let queryTypes = "";
  if (querySchemas && Object.keys(querySchemas).length > 0) {
    const queryEntries = Object.entries(querySchemas)
      .map(([queryKey, schema]) => {
        const { node } = zodToTs(schema, { auxiliaryTypeStore });
        const typeString = printNode(node);
        return `    ${queryKey}: ${indentType(typeString, "    ")};`;
      })
      .join("\n");

    queryTypes = `\n  interface QueryRegistry {\n${queryEntries}\n  }\n`;
  }

  const content = `// Auto-generated by AppKit - DO NOT EDIT
// Generated at: ${new Date().toISOString()}

import "@databricks/app-kit-ui/react";

${auxiliaryPreamble}declare module "@databricks/app-kit-ui/react" {
  interface PluginRegistry {
${pluginTypes}
  }
${queryTypes}
}
`;

  const configDir = path.join(process.cwd(), "config");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  const filePath = path.join(configDir, "appKitTypes.d.ts");
  fs.writeFileSync(filePath, content, "utf-8");

  console.log(`[AppKit] Plugin types generated: ${filePath}`);
}
