import fs from "node:fs";
import path from "node:path";
import type { QuerySchemas } from "shared";
import { createAuxiliaryTypeStore, printNode, zodToTs } from "zod-to-ts";
import { routeSchemaRegistry } from "../plugin";

interface PluginTypeInfo {
  name: string;
}

function indentType(typeString: string, baseIndent: string): string {
  const lines = typeString.split("\n");
  if (lines.length === 1) return typeString;

  return lines
    .map((line, index) => (index === 0 ? line : baseIndent + line))
    .join("\n");
}

export function generatePluginTypes(
  plugins: PluginTypeInfo[],
  querySchemas: QuerySchemas,
  fePath?: string,
): void {
  const auxiliaryTypeStore = createAuxiliaryTypeStore();

  const pluginTypes = plugins
    .map((p) => {
      const routes = routeSchemaRegistry.get(p.name);
      if (!routes || routes.size === 0) return null;

      const routeTypes = Array.from(routes.entries())
        .map(([route, schema]) => {
          const { node } = zodToTs(schema, { auxiliaryTypeStore });
          const typeString = printNode(node);
          return `      "${route}": ${indentType(typeString, "      ")};`;
        })
        .join("\n");
      return `    ${p.name}: {\n${routeTypes}\n    }`;
    })
    .filter(Boolean)
    .join("\n");

  let queryTypes = "";
  if (querySchemas && Object.keys(querySchemas).length > 0) {
    const queryEntries = Object.entries(querySchemas)
      .map(([queryKey, schema]) => {
        const { node } = zodToTs(schema, { auxiliaryTypeStore });
        const typeString = printNode(node);
        return `    ${queryKey}: ${indentType(typeString, "    ")};`;
      })
      .join("\n");

    queryTypes = `\n  interface QueryRegistry {\n${queryEntries}\n  }\n`;
  }

  const content = `// Auto-generated by AppKit - DO NOT EDIT
import "@databricks/app-kit-ui/react";

declare module "@databricks/app-kit-ui/react" {
  interface PluginRegistry {
${pluginTypes}
  }
${queryTypes}
}
`;

  const defaultPath = path.join(process.cwd(), "client", "src");
  const clientSrcDir = fePath ? fePath.replace(/dist$/, "src") : defaultPath;

  if (!fs.existsSync(clientSrcDir)) {
    console.log(
      `[AppKit] Client src dir not found: ${clientSrcDir}, skipping type generation`,
    );
    return;
  }

  const filePath = path.join(clientSrcDir, "appKitTypes.d.ts");
  fs.writeFileSync(filePath, content, "utf-8");
  console.log(`[AppKit] Plugin types generated: ${filePath}`);
}
