import fs from "node:fs/promises";
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import {
  CACHE_VERSION,
  endpointIdentityHash,
  loadServingCache,
} from "../cache";

vi.mock("node:fs/promises");

describe("serving cache", () => {
  beforeEach(() => {
    vi.mocked(fs.mkdir).mockResolvedValue(undefined);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe("endpointIdentityHash", () => {
    test("returns a consistent SHA256 hash for the same alias + endpoint", () => {
      const hash1 = endpointIdentityHash("chat", "my-endpoint");
      const hash2 = endpointIdentityHash("chat", "my-endpoint");
      expect(hash1).toBe(hash2);
      expect(hash1).toHaveLength(64); // SHA256 hex
    });

    test("different alias or endpoint produces different hashes", () => {
      expect(endpointIdentityHash("chat", "a")).not.toBe(
        endpointIdentityHash("chat", "b"),
      );
      expect(endpointIdentityHash("a", "ep")).not.toBe(
        endpointIdentityHash("b", "ep"),
      );
    });
  });

  describe("loadServingCache", () => {
    test("returns empty cache when file does not exist", async () => {
      vi.mocked(fs.readFile).mockRejectedValue(
        Object.assign(new Error("ENOENT"), { code: "ENOENT" }),
      );

      const cache = await loadServingCache("/out/serving.d.ts");
      expect(cache).toEqual({ version: CACHE_VERSION, endpoints: {} });
    });

    test("reconstructs the cache from a committed serving.d.ts header + body", async () => {
      const hash = endpointIdentityHash("chat", "my-endpoint");
      const file = `// Auto-generated by AppKit — DO NOT EDIT
// Regenerate with: npx @databricks/appkit generate-types
//
// ── typegen cache · v${CACHE_VERSION} · appkit@0.0.0 · 2026-01-01T00:00:00Z ──
// A matching endpoint-identity hash skips the serving fetch on build & deploy.
//   chat    my-endpoint    ${hash}
// ${"─".repeat(60)}
import "@databricks/appkit";
import "@databricks/appkit-ui/react";

declare module "@databricks/appkit" {
  interface ServingEndpointRegistry {
    chat: {
      request: { messages: string[] };
      response: { model: string };
      chunk: unknown;
    };
  }
}

declare module "@databricks/appkit-ui/react" {
  interface ServingEndpointRegistry {
    chat: {
      request: { messages: string[] };
      response: { model: string };
      chunk: unknown;
    };
  }
}
`;
      vi.mocked(fs.readFile).mockResolvedValue(file);

      const cache = await loadServingCache("/out/serving.d.ts");
      expect(cache.version).toBe(CACHE_VERSION);
      expect(cache.endpoints.chat.hash).toBe(hash);
      expect(cache.endpoints.chat.member).toContain("request: {");
      expect(cache.endpoints.chat.member).toContain("messages: string[]");
    });

    test("returns empty cache when the header version mismatches", async () => {
      const file = `// ── typegen cache · v0 · appkit@0.0.0 · 2026-01-01T00:00:00Z ──
// explainer
//   chat    my-endpoint    deadbeef
// ${"─".repeat(60)}
import "@databricks/appkit";
`;
      vi.mocked(fs.readFile).mockResolvedValue(file);

      const cache = await loadServingCache("/out/serving.d.ts");
      expect(cache).toEqual({ version: CACHE_VERSION, endpoints: {} });
    });

    test("returns empty cache when the file has no header", async () => {
      vi.mocked(fs.readFile).mockResolvedValue("export const x = 1;\n");

      const cache = await loadServingCache("/out/serving.d.ts");
      expect(cache).toEqual({ version: CACHE_VERSION, endpoints: {} });
    });
  });
});
