import { describe, expect, test } from "vitest";
import {
  type CacheHeaderEntry,
  deindentBlock,
  objectMemberValue,
  objectTopLevelKeys,
  parseCacheHeader,
  renderCacheHeader,
  resolveHeaderTimestamp,
  splitEntryBlocks,
} from "../embedded-cache";

/**
 * This module encodes the typegen cache INTO a generated `.d.ts` and decodes it
 * back out. The block below is what a real committed `analytics.d.ts` looks
 * like — a header comment (the cache) plus the module augmentation (the body):
 *
 *   // Auto-generated by AppKit — DO NOT EDIT
 *   // Regenerate with: npx @databricks/appkit generate-types
 *   //
 *   // ── typegen cache · v3 · appkit@0.48.0 · 2026-01-01T00:00:00.000Z ──
 *   // A matching source hash skips the warehouse DESCRIBE on build & deploy.
 *   //   apps_list    9f0e7a21c4d3b2a1
 *   //   revenue      44de1b90c7f2e3a1
 *   // ────────────────────────────────────────────────────────────
 *   import "@databricks/appkit-ui/react";
 *   declare module "@databricks/appkit-ui/react" {
 *     interface QueryRegistry {
 *       apps_list: { name: "apps_list"; result: Array<{ id: string }>; };
 *       revenue:   { name: "revenue";   result: Array<{ arr: number }>; };
 *     }
 *   }
 *
 * The lifecycle test below reproduces exactly how a subsystem generator uses
 * these functions: render a file, then on the next run parse the header + split
 * the body to serve cache hits without re-describing.
 */

const TS = "2026-01-01T00:00:00.000Z";

// Build a full generated-file string: header (from renderCacheHeader) + body.
const sampleFile = (entries: CacheHeaderEntry[], body: string) =>
  `${renderCacheHeader({
    version: "3",
    explainer: "A matching source hash skips the DESCRIBE.",
    timestamp: TS,
    toolVersion: "9.9.9",
    entries,
  })}${body}`;

describe("cache lifecycle: encode a generated file, then decode it back", () => {
  test("render → parse header + split body recovers each entry's hash and block", () => {
    // ── Run 1: the generator renders a file for two described queries. ──
    // Each entry contributes a header line (name + hash) and a body member
    // (the rendered TypeScript block).
    const entries: CacheHeaderEntry[] = [
      { name: "apps_list", hash: "9f0e7a21c4d3b2a1" },
      { name: "revenue", hash: "44de1b90c7f2e3a1" },
    ];
    const body = `import "@databricks/appkit-ui/react";
declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    apps_list: {
      name: "apps_list";
      result: Array<{ id: string }>;
    };
    revenue: {
      name: "revenue";
      result: Array<{ arr: number }>;
    };
  }
}
`;
    const committedFile = sampleFile(entries, body);

    // ── Run 2: the generator reads the committed file back. ──
    // Step A — parseCacheHeader recovers the name → hash map (the change
    // detector). A generator compares each of these to the current source hash.
    const header = parseCacheHeader(committedFile);
    expect(header.version).toBe("3");
    expect(header.timestamp).toBe(TS);
    expect(header.hashes).toEqual({
      apps_list: "9f0e7a21c4d3b2a1",
      revenue: "44de1b90c7f2e3a1",
    });

    // Step B — splitEntryBlocks recovers each entry's rendered block. On a
    // cache HIT the generator reuses this verbatim instead of re-describing.
    const blocks = splitEntryBlocks(committedFile, "QueryRegistry");
    expect(Object.keys(blocks).sort()).toEqual(["apps_list", "revenue"]);
    expect(blocks.apps_list).toContain('name: "apps_list"');
    expect(blocks.revenue).toContain("arr: number");

    // Step C — the generator's cache lookup: for a given query name, a HIT is
    // "header hash matches the current source AND a body block exists".
    const isHit = (name: string, currentHash: string) =>
      header.hashes[name] === currentHash && blocks[name] !== undefined;
    expect(isHit("apps_list", "9f0e7a21c4d3b2a1")).toBe(true); // unchanged
    expect(isHit("revenue", "different-hash")).toBe(false); // edited → re-describe
    expect(isHit("new_query", "whatever")).toBe(false); // not in cache
  });
});

describe("renderCacheHeader / parseCacheHeader", () => {
  test("an empty entry list renders and parses with no hashes", () => {
    const file = sampleFile([], "export {};\n");
    expect(file).toContain("(no cached entries)");
    const parsed = parseCacheHeader(file);
    expect(parsed.version).toBe("3");
    expect(parsed.hashes).toEqual({});
  });

  test("a decorative detail column is preserved in the render but ignored on parse", () => {
    const file = sampleFile(
      [
        {
          name: "revenue",
          detail: "cat.sch.rev · sp",
          hash: "44de1b90c7f2e3a1",
        },
      ],
      "",
    );
    // The detail is shown to human readers ...
    expect(file).toContain("cat.sch.rev · sp");
    // ... but the parser reads only the first (name) and last (hash) tokens.
    expect(parseCacheHeader(file).hashes).toEqual({
      revenue: "44de1b90c7f2e3a1",
    });
  });

  test("a file with no header parses as empty (all-miss), never throws", () => {
    const parsed = parseCacheHeader("// just some code\nexport const x = 1;\n");
    expect(parsed.version).toBeNull();
    expect(parsed.hashes).toEqual({});
  });

  test("the explainer line is never mistaken for an entry", () => {
    const parsed = parseCacheHeader(
      sampleFile([{ name: "q", hash: "abcd12" }], ""),
    );
    expect(Object.keys(parsed.hashes)).toEqual(["q"]);
  });
});

describe("splitEntryBlocks", () => {
  const body = `import "x";
declare module "m" {
  interface QueryRegistry {
    apps_list: {
      name: "apps_list";
      result: Array<{ id: string; note: "a }{ brace in string" }>;
    };
    other: {
      name: "other";
      result: unknown;
    };
  }
}
`;

  test("splits members by top-level key, ignoring braces inside strings", () => {
    const blocks = splitEntryBlocks(body, "QueryRegistry");
    expect(Object.keys(blocks).sort()).toEqual(["apps_list", "other"]);
    expect(blocks.apps_list).toContain('name: "apps_list"');
    // The `}{` inside the string literal must not end the member early.
    expect(blocks.apps_list).toContain("a }{ brace in string");
  });

  test("returns {} when the interface is absent", () => {
    expect(splitEntryBlocks(body, "NopeRegistry")).toEqual({});
  });

  test("a member literally named __proto__ is an own key (no pollution)", () => {
    const proto = `declare module "m" {
  interface R {
    "__proto__": { a: 1 };
    normal: { b: 2 };
  }
}`;
    const blocks = splitEntryBlocks(proto, "R");
    expect(Object.hasOwn(blocks, "__proto__")).toBe(true);
    expect(Object.hasOwn(blocks, "normal")).toBe(true);
    // Object.prototype was not mutated.
    expect(({} as Record<string, unknown>).a).toBeUndefined();
  });
});

describe("objectTopLevelKeys / objectMemberValue (serving request allowlist)", () => {
  // A serving member's rendered block: the request param allowlist is the set
  // of top-level keys of its `request` object type.
  const block = `{
      request: { messages: string[]; temperature: number };
      response: { model: string };
      chunk: unknown;
    }`;

  test("objectMemberValue returns the raw value text of a member", () => {
    expect(objectMemberValue(block, "request")).toBe(
      "{ messages: string[]; temperature: number }",
    );
    expect(objectMemberValue(block, "chunk")).toBe("unknown");
    expect(objectMemberValue(block, "nope")).toBeUndefined();
  });

  test("objectTopLevelKeys returns only the outermost keys", () => {
    const request = objectMemberValue(block, "request") ?? "";
    // `messages` and `temperature` — NOT the nested keys inside them.
    expect(objectTopLevelKeys(request)).toEqual(["messages", "temperature"]);
  });

  test("a generic Record request has no top-level keys (passthrough)", () => {
    expect(objectTopLevelKeys("Record<string, unknown>")).toEqual([]);
  });
});

describe("deindentBlock", () => {
  test("strips up to n leading spaces from lines 2..N, leaving line 1 intact", () => {
    const block = "{\n      x: 1;\n    }";
    // n=4: line 2 "      x" loses 4 spaces → "  x"; line 3 "    }" loses 4 → "}".
    expect(deindentBlock(block, 4)).toBe("{\n  x: 1;\n}");
  });
});

describe("resolveHeaderTimestamp (stable timestamp ⇒ byte-identical unchanged runs)", () => {
  const entries: CacheHeaderEntry[] = [{ name: "q", hash: "abcd12" }];

  test("preserves the prior timestamp when the entry set is unchanged", () => {
    const prior = sampleFile(entries, "");
    expect(resolveHeaderTimestamp(prior, entries)).toBe(TS);
  });

  test("returns a fresh timestamp when a hash changed", () => {
    const prior = sampleFile(entries, "");
    const next = resolveHeaderTimestamp(prior, [{ name: "q", hash: "ffff99" }]);
    expect(next).not.toBe(TS);
  });

  test("returns a fresh timestamp when an entry is added", () => {
    const prior = sampleFile(entries, "");
    const next = resolveHeaderTimestamp(prior, [
      ...entries,
      { name: "q2", hash: "0011aa" },
    ]);
    expect(next).not.toBe(TS);
  });

  test("returns a fresh timestamp when there is no prior header", () => {
    expect(resolveHeaderTimestamp("", entries)).not.toBe(TS);
  });
});
