import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const componentDir = path.join(repoRoot, "packages/appkit-ui/src/react/ui");
const mapDir = path.join(componentDir, "examples");
const tmpExamplesDir = path.join(repoRoot, "tmp/examples");

const componentNames = readdirSync(componentDir, { withFileTypes: true })
  .filter((entry) => entry.isFile() && entry.name.endsWith(".tsx"))
  .map((entry) => entry.name.replace(/\.tsx$/, ""))
  .filter((name) => name !== "index");

const pascalCase = (value: string) =>
  value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map(
      (segment) =>
        `${segment[0].toUpperCase()}${segment.slice(1)}`,
    )
    .join("");

const matches: string[] = [];
const mapEntries: {
  key: string;
  importName: string;
  source: string;
}[] = [];

for (const componentName of componentNames) {
  const demoName = `${componentName}-demo.tsx`;
  const sourcePath = path.join(tmpExamplesDir, demoName);
  if (!existsSync(sourcePath)) {
    continue;
  }

  let source = readFileSync(sourcePath, "utf8");
  source = source.replace(/@\/registry\/default\/ui\//g, "./");
  source = source.replace(/@\/lib\/utils/g, "../lib/utils");
  source = source.replace(/@\/components\/icons/g, "../../components/icons");
  source = source.replace(/@\/js\//g, "../../js/");

  const pascal = pascalCase(componentName);
  source = source.replace(
    /export default function\s+\w+/,
    `export default function ${pascal}Example`,
  );

  const outputPath = path.join(componentDir, `${componentName}.example.tsx`);
  writeFileSync(outputPath, source, "utf8");
  matches.push(componentName);
  mapEntries.push({
    key: componentName,
    importName: `${pascal}Example`,
    source,
  });
}

if (existsSync(mapDir)) {
  rmSync(mapDir, { recursive: true, force: true });
}

mkdirSync(mapDir, { recursive: true });

const sortedMapEntries = [...mapEntries].sort((a, b) =>
  a.key.localeCompare(b.key),
);

const importStatements = sortedMapEntries
  .map((entry) => `import ${entry.importName} from "../${entry.key}.example";`)
  .join("\n");

const entries = sortedMapEntries
  .map(
    (entry) => `  "${entry.key}": {
    Component: ${entry.importName},
    source: ${JSON.stringify(entry.source)},
  },`,
  )
  .join("\n");

const indexContent = `/* Autogenerated by tools/sync-appkit-examples.ts */
import type { ComponentType } from "react";

${importStatements}

export type AppKitExampleEntry = {
  Component: ComponentType;
  source: string;
};

export const examples: Record<string, AppKitExampleEntry> = {
${entries}
};

export type AppKitExampleKey = keyof typeof examples;
`;

writeFileSync(path.join(mapDir, "index.ts"), indexContent, "utf8");

console.log(
  `Copied ${matches.length} example files and wrote ${mapEntries.length} map entries to ${mapDir}`,
);
if (matches.length === 0) {
  console.warn("No example files matched the component list.");
}

