import type { AgentToolDefinition } from "shared";

/**
 * A connected browser tab's tool surface. The browser opens a persistent SSE
 * channel (storing `push`) and registers its live catalog (`tools`). Both the
 * in-app chat agent and the MCP bridge read the catalog from here and deliver
 * tool calls back to the tab through `push` — so the per-request `uiTools`
 * body field is gone and there is a single shared executor.
 */
export interface ToolSession {
  sessionId: string;
  userId: string;
  tools: AgentToolDefinition[];
  /** Push an SSE event down the tab's channel. Undefined until the channel opens. */
  push?: (event: Record<string, unknown>) => void;
  lastSeen: number;
}

/**
 * In-memory registry of connected browser tabs and their UI tool catalogs.
 * One entry per `sessionId` (generated by the browser on load). Survives
 * across chat requests — registration is persistent, not per-request.
 *
 * Not persisted: sessions are live connections; on server restart every tab
 * reconnects and re-registers.
 */
export class ToolSessionRegistry {
  private sessions = new Map<string, ToolSession>();

  /** Upsert helper — preserves any fields already known for the session. */
  private upsert(sessionId: string, patch: Partial<ToolSession>): ToolSession {
    const existing = this.sessions.get(sessionId);
    const next: ToolSession = {
      sessionId,
      userId: patch.userId ?? existing?.userId ?? "",
      tools: patch.tools ?? existing?.tools ?? [],
      push: "push" in patch ? patch.push : existing?.push,
      lastSeen: Date.now(),
    };
    this.sessions.set(sessionId, next);
    return next;
  }

  /**
   * Attach (or replace, on reconnect) the live SSE channel for a session.
   * Returns the session so the caller can seed it.
   */
  openChannel(
    sessionId: string,
    userId: string,
    push: (event: Record<string, unknown>) => void,
  ): ToolSession {
    return this.upsert(sessionId, { userId, push });
  }

  /** Drop the channel + session when the tab disconnects. */
  closeChannel(sessionId: string): void {
    this.sessions.delete(sessionId);
  }

  /** Replace the registered tool catalog for a session. */
  setTools(
    sessionId: string,
    userId: string,
    tools: AgentToolDefinition[],
  ): ToolSession {
    return this.upsert(sessionId, { userId, tools });
  }

  get(sessionId: string): ToolSession | undefined {
    const s = this.sessions.get(sessionId);
    if (s) s.lastSeen = Date.now();
    return s;
  }

  /** The most-recently-active session (for MCP, which has no session id of its own). */
  latest(): ToolSession | undefined {
    let best: ToolSession | undefined;
    for (const s of this.sessions.values()) {
      if (s.push && (!best || s.lastSeen > best.lastSeen)) best = s;
    }
    return best;
  }

  /** All live sessions with an open channel. */
  list(): ToolSession[] {
    return Array.from(this.sessions.values()).filter((s) => s.push);
  }

  get size(): number {
    return this.sessions.size;
  }
}
