import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import typedocSidebar from "./docs/api/appkit/typedoc-sidebar";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const SUPPORTED_KINDS = new Set([
  "class",
  "interface",
  "typealias",
  "function",
  "variable",
  "enum",
]);

function flattenSidebarWithKind(sidebarConfig: any): any[] {
  const flatItems: any[] = [];
  const items = Array.isArray(sidebarConfig)
    ? sidebarConfig
    : sidebarConfig.items || [];

  for (const item of items) {
    if (item.type === "category" && item.items) {
      // Extract items from categories
      for (const subItem of item.items) {
        // Extract kind from the id (e.g., "Function." from "api/appkit/Function.name")
        // To get "function", "class", "interface", etc.
        const idParts = subItem.id.split("/").pop() || "";
        const rawKind = idParts.split(".")[0].toLowerCase();
        const kind = SUPPORTED_KINDS.has(rawKind) ? rawKind : "other";

        flatItems.push({
          ...subItem,
          className: `api-kind-${kind}`,
        });
      }
    } else {
      flatItems.push(item);
    }
  }

  return flatItems;
}
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [
        {
          type: "category",
          label: "@databricks/appkit",
          link: {
            type: "doc",
            id: "api/appkit/index",
          },
          items: flattenSidebarWithKind(typedocSidebar),
        },
      ],
    },
  ],
};

export default sidebars;
