import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import typedocSidebar from "./docs/api/app-kit/typedoc-sidebar";
import uiTypedocSidebar from "./docs/api/app-kit-ui/typedoc-sidebar";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [
        {
          type: "category",
          label: "@databricks/app-kit",
          link: {
            type: "doc",
            id: "api/app-kit/index",
          },
          items: typedocSidebar.items,
        },
        {
          type: "category",
          label: "@databricks/app-kit-ui",
          link: {
            type: "doc",
            id: "api/app-kit-ui/index",
          },
          items: uiTypedocSidebar.items,
        },
      ],
    },
  ],
};

export default sidebars;
